source/docs/colors.blade.md
I found this tiny typo and I thought it would be a good way to start trying to contribute to open source
=> Fix typo in the Colors page

source/index.blade.php
This PR fixes this:
Seems to be fixed already, but this will use my current Gravatar.
=> Set David's image to his Gravatar

source/docs/cursor.blade.md
Adds [`.cursor-default`](https://github.com/tailwindcss/tailwindcss/blob/master/src/generators/cursor.js#L6) to the cursor documentation.
=> Add .cursor-default

source/docs/installation.blade.md
The [Phoenix web framework](http://phoenixframework.org/) uses [Brunch](https://brunch.io/) by default for asset processing so adding these instructions should prove useful for folks wanting to get going with Tailwind in an out-of-the-box Phoenix project (as well as for those simply using Brunch of their own accord).
=> Add installation instructions for Brunch

package.json, yarn.lock
The version displayed on the website is still 0.5.2 and not the current version 0.5.3. So I updated the required version in package.json as well as in the yarn.lock file
=> updated version from 0.5.2 to 0.5.3

source/docs/background-color.blade.md, source/docs/border-color.blade.md, source/docs/font-weight.blade.md, source/docs/shadows.blade.md, source/docs/state-variants.blade.md, source/docs/text-color.blade.md, source/docs/text-style.blade.md
Bring consistency with tailwindcss/tailwindcss#498
BTW: When checking all docs, I across the fact that there aren't any docs for `borderCollapse` & `outline`
=> Enable more variants by default

source/docs/spacing.blade.md
I found this tiny typo in the spacing page.
=> Fix typo in space 20 size

source/docs/controlling-file-size.blade.md
This fixes some issues people have been having. The regex `A-z` matches some symbols that might be unexpected, I found these but there could be more: *`[]\-_^* 
thats why we have changed it to *A-Za-z_*
=> Update purgecss suggested regex extractor.

source/docs/shadows.blade.md
The shadow-outline value matches the current 0.6.1 default value. Also added outline to the customizing section.
=> Updated shadow-outline from 0.6.1 fix

source/docs/installation.blade.md
Add instructions on how to install Tailwind with Webpack Encore for Symfony projects.
=> Add Webpack Encore installation instructions

source/docs/installation.blade.md
Recommend filename is `tailwind.js` so all examples should include this filename and not `tailwind-config.js` as before.
=> Changed filename of default config in examples

source/docs/controlling-file-size.blade.md
I've added the new location of the JS directory for Laravel 5.7.* so the example will work out of the box for newer projects (After learning that it didn't work for them the hard way).
I figured it made sense to also keep the old path for backwards compatibility.
=> Add new Laravel JS structure to the PurgeCSS docs

source/docs/text-color.blade.md
The hover section incorrectly specifies `:focus` instead of `:hover`.
=> Fix wrong pseudo-class

source/docs/installation.blade.md
The `npx` command already integrated in `npm` since [v5.2.0 (July 2017)](https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner). I think it is safe to replace `node_modules/.bin/tailwind` with `npx tailwind`.
=> Use npx instead of node_modules/.bin

source/docs/installation.blade.md
In "Create a Tailwind config file" you used `npx tailwind` instead of `./node_modules/.bin/tailwind`, which was a good change. For consistency, the same change should be made in the "Using Tailwind CLI" section.
=> Use npx to execute tailwind

source/docs/configuration.blade.md
Same documention suggestion as in https://github.com/tailwindcss/tailwindcss/pull/368.
A documentation suggestion for the "function as prefix" feature. Happy to change anything if it's not to your liking.
=> Document the function prefix feature

source/docs/examples/forms.blade.md, source/docs/examples/navigation.blade.md, source/docs/flexbox-flex-grow-shrink.blade.md, source/docs/state-variants.blade.md
This PR renames the classes `flex-no-grow` and `flex-no-shrink` to `flex-grow-0` and `flex-shrink-0`, as per https://github.com/tailwindcss/tailwindcss/pull/687
=> Rename the `flex-no-[grow/shrink]` classnames to `flex-[grow/shrink]-0` (#687)

source/docs/positioning.blade.md
Renaming the` .pin-{side}` utilities to `.{top|right|bottom|left|inset}-{value}`: [#764](https://github.com/tailwindcss/tailwindcss/pull/764)
=> Updated position page (#764)

source/docs/background-color.blade.md, source/docs/border-color.blade.md, source/docs/text-color.blade.md
The color tables currently display a JSON string for all colors except transparent, white and black. This PR fixes that by introducing an extra `mapWithKeys` call to split out the color collections before formatting them.
=> Fix border, text and background color tables

source/docs/fonts.blade.md
The font families page now reads the stacks directly from the theme configuration, ensuring that they are always up-to-date with the latest configuration changes.
=> Update font families page

source/docs/background-color.blade.md, source/docs/border-color.blade.md, source/docs/text-color.blade.md
The `transparent`, `black`, and `white` colors were missing a trailing semicolon on the background/border/text color pages.
=> Add missing semicolons on color pages

source/docs/lists.blade.md
This PR documents the new list utilities and updates the examples to show how to add back the default browser styling to lists.
One thing I found when documenting this is that the 'variants and disabling' partial currently does not allow specifying multiple plugins. This will be required because of the new split from `lists` to `listStylePosition` and `listStyleType` (and others).
=> Document new list utilities

source/docs/background-color.blade.md, source/docs/border-color.blade.md
On the background and border color pages the code for the transparent/black/white colors incorrectly display as `color` instead of `background-color` and `border-color`.
=> Fix incorrect CSS code for background and border base colors

source/_assets/js/components/TableOfContents.vue
H5 elements in the sidebars have bugged and unnecessary anchors. Now anchors will only be added to H2 and H3 elements.
Another option might be a `.no-anchor` class on said elements.
=> Only add anchors to H2 and H3

source/docs/plugins.blade.md
Since, by default, the Tailwind separator that needs to be escaped wanted to make sure that was reflected in the docs.
=> Escape separators in custom variant code examples

source/docs/configuration.blade.md
rename `modules` key to `variants` in the disable module section of configuration page.`
=> Rename `modules` to `variants`

navigation.php, source/docs/flexbox-flex-grow.blade.md, source/docs/flexbox-flex-shrink.blade.md, source/docs/flexbox-flex.blade.md
This PR splits up the 'Flex, Grow, & Shrink' page into a 'Flex', 'Flex Grow', and 'Flex Shrink' page to document the new customization possibilities.
=> Split Flex, Grow, & Shrink into separate pages

config.php
The new flex page structure (#121) causes the 'Flex' page to also be highlighted when visiting the 'Flex Grow' and 'Flex Shrink' pages. This PR fixes that.
It could possibly be simplified further by just doing `return $page->getPath() === $path;` without the collection wrapping and contains loop, but I wasn't sure if there is any current behavior that relies on this.
=> Fix incorrect active page highlighting

source/docs/display.blade.md
This PR documents the `.block`, `.inline-block`, `.inline`, `.table`, `.table-row`, `.table-cell`, and `.hidden` display utilities.
=> Document all display utilities

source/docs/object-fit.blade.md
This adds a usage example to the Object Fit page.  It is based on the old example from https://github.com/tailwindcss/plugin-examples.  Lemme know if you want me to change the url of the sample image to something else.  Also let me know if you want me to remove the "work in progress".
=> Add object-fit usage example

source/docs/font-family.blade.md
This PR documents the responsive features of the font family utilities, and also fixed the reference to the `fonts` property which was renamed to `fontFamily`.
=> Update font family documentation

source/docs/font-weight.blade.md
This PR updates the font weight documentation to add customization options, and also fixes the reference to the `fontWeights` property which was renamed to `fontWeight`.
=> Update font weight documentation

source/docs/line-height.blade.md
This PR updates the line height documentation to add customization options, and also fixes the reference to the `leading` property which was renamed to `lineHeight`.
=> Update line height documentation

source/docs/controlling-file-size.blade.md
- Updated code samples to use 1.0 config
- Removed a code sample using _.pick to pick theme colors to apply to textColor. It was a straightforward example when the colors object was only one level deep but it's more complicated now when trying to select colors.gray.700 for example. This page is probably not the best place for such a problem, I imagine.
- Changed references from modules to variants
- Updated build sizes — calculations made using [this tool](https://github.com/davecalnan/measure-tailwindcss-build-size)
The build sizes seem to be a bit larger for me. Would love if someone could look over to confirm!
Fixes #136
=> Controlling File Size page

source/_partials/customized-config.blade.php, source/docs/background-color.blade.md, source/docs/background-position.blade.md, source/docs/background-size.blade.md, source/docs/border-color.blade.md, source/docs/border-radius.blade.md, source/docs/border-width.blade.md, source/docs/box-shadow.blade.md, source/docs/cursor.blade.md, source/docs/fill.blade.md, source/docs/flex-grow.blade.md, source/docs/flex-shrink.blade.md, source/docs/flex.blade.md, source/docs/font-family.blade.md, source/docs/font-weight.blade.md, source/docs/height.blade.md, source/docs/line-height.blade.md, source/docs/list-style-type.blade.md, source/docs/max-width.blade.md, source/docs/object-position.blade.md, source/docs/opacity.blade.md, source/docs/stroke.blade.md, source/docs/text-color.blade.md, source/docs/width.blade.md, source/docs/z-index.blade.md
Sorry for the big commit, if you want me to split it up into separate ones let me know.
This PR updates the customized-config partial to support a variable amount of nested keys, and also adds the `usesTheme` option to control the output of the `theme => ({` closure.
I've also updated all the uses of the partial to include the `theme` key where applicable.
=> Update customized-config partial to support nested keys

source/docs/margin.blade.md
This PR updates the margin documentation to add customization and responsive features.
I noticed in the Fill documentation that you used the `theme` key for the customized config partial and decided to apply this as well. Do you think the partial should be updated to always include the theme key, as it should probably apply to all of them?
**Edit:** updated to use the new customized-config syntax
=> Update margin documentation

source/docs/position.blade.md, source/docs/top-right-bottom-left.blade.md
This PR removes the top/right/bottom/left utilities and examples from the Position docs, and changes the responsive examples to focus more on the `position` property.
It also updates the responsive examples and adds customization documentation to the top/right/bottom/left page
=> Update position documentation

source/docs/upgrading-to-v1.blade.md
The last diff in section 2.7 was removing the matching square bracket for the plugins section
=> Fix plugins diff in section 2.7

source/docs/functions-and-directives.blade.md
Focus utilities have to come AFTER hover utilities in the list if they should take priority over hover utilities.
=> Correct logical mistake concerning priority

source/docs/whitespace.blade.md, source/docs/word-break.blade.md
Document all whitespace and word break utilities and add responsive examples. This finishes the 'Typography' section of the documentation
=> Finish whitespace and word break docs

source/docs/margin.blade.md, source/docs/negative-margin.blade.md, source/docs/padding.blade.md
Added customization and responsive examples. Also fixed a bug where the `auto` and `px` utilities were only shown for the `ml`, `pl`, and `-ml` variants.
=> Update padding, margin, and negative margin docs

source/docs/word-break.blade.md
It should be "break-all" in the example, not "break-words"
=> Fix an error

source/docs/background-color.blade.md
In the hover section it says "before the focus: prefix" when it should say "hover: prefix"
=> Update Hover section in Background-color doc file 

source/docs/cursor.blade.md
:wave:
Here are some examples for using the `cursor-{style}` utilities.
Used as reference for some of the more esoteric terms (TIL: `cursor-text` is an 'I-beam'):
- https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
- https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/mouse-and-trackpad/#pointers
- https://docs.microsoft.com/en-us/windows/desktop/uxguide/inter-mouse#common-pointer-shapes
Preview: https://deploy-preview-184--elated-stonebraker-70896a.netlify.com/docs/cursor
=> Add usage examples for cursors

source/docs/installation.blade.md
Updates the Laravel Mix docs link from:
```
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/css-preprocessors.md#css-url-rewriting
```
to
```
https://laravel-mix.com/docs/4.0/css-preprocessors#css-url-rewriting
```
=> Updates Laravel Mix documentation link.

.editorconfig, source/docs/configuration.blade.md, source/docs/theme.blade.md, source/docs/upgrading-to-v1.blade.md
- Change URL references from next to master
- Set trim_trailing_whitespace to false for `*.md` files (otherwise linebreaks get broken on save via editorconfig plugins)
=> Change URL references from next to master

source/docs/upgrading-to-v1.blade.md
Just using `npm install tailwindcss --save-dev` on an existing project which is what this guide is for won’t work — you’ll just get the latest version available for your version range.
=> Proper npm command for upgrading to 1.0

source/docs/installation.blade.md
On the installation example page the Ember.js example is not syntax highlighting correctly. 
Adding `js` to the code block fixes the issue
=> add js to ember code example

source/docs/upgrading-to-v1.blade.md
This is probably not necessary for reasonable minded folk, but I followed the conversions idiomatically and ended up with `text-white-500` . I don't think an explicit sentence to say it has not changed is necessary, but just being in there might save people a few minutes.
=> Mention keeping white as white

source/docs/customizing-colors.blade.md
Destructuring should be used in the colors object, not theme, otherwise it will generate the colors classes twice.
=> Fix destructuring the colors object

source/docs/plugins.blade.md
The `e` function must be destructured in order to use it here.
=> Destructure escape function

source/docs/word-break.blade.md
`break-all` sets the `word-break: break-all` styling as opposed to the `word-break: normal` the docs talk about
=> use correct break-all wordbreak css

package.json, source/_layouts/documentation.blade.php, source/_layouts/homepage.blade.php
This PR updates tailwindcss to 1.0.2 and uses the same `$page->version` where needed.
=> Update to v1.0.2

source/docs/z-index.blade.md
The customized config example had `theme.margin` instead of `theme.zIndex`.
=> Fix typo in z-index.blade.md

source/docs/pseudo-class-variants.blade.md
The given example was not working with the given example, not it is.
=> Make the example code workable

source/docs/top-right-bottom-left.blade.md
=> Fix typo in negative top right bottom left example code

source/docs/functions-and-directives.blade.md
As discussed in https://github.com/tailwindcss/tailwindcss/issues/993 this caveat is mentioned in the docs but on another page. This PR should improve ability to find this information.
=> Add note about interpolation of !important in Sass/SCSS

source/components.blade.md
In [one example there is `focus:outline-0`](https://tailwindcss.com/components) used instead of [the official `focus:outline-none`](https://tailwindcss.com/docs/outline/#app). I have changed it and verified locally it works as expected.
The preview of the change on Netlify: [here](https://deploy-preview-260--elated-stonebraker-70896a.netlify.com/components).
=> Fixed misleading usage of outline-0

source/docs/configuration.blade.md
This adds the `order` to the list of core plugins on the Configuration page.
=> Added flexbox items order to core plugins list

source/course/optimizing-for-production.blade.md
The "Next Lesson" link on the "Optimizing for Production" screencast still points to the "We're still working on this one!" page even though the content is already available.
=> Fix "Next Lesson" link

source/docs/controlling-file-size.blade.md
A Vue.js component can have the following attribute: `:class="{ invisible: someCondition }"` (sometimes even enforce by some linters)
With the current suggested regex `[A-Za-z0-9-_:/]+`, the whole `invisible:` word is interpreted as a class and the `invisible` class will be stripped away.
Changing the regex to prevent the `:` from being at the last position solves this issue: `[A-Za-z0-9-_:/]*[A-Za-z0-9-_/]`
I am not aware of any tailwind class ending with `:` (which this MR would break) and I think that someone generating such classes intentionally should be skilled enough to also adapt this regex to its usecase :-)
=> Refine purgecss defaultExtractor regex for vuejs

source/docs/theme.blade.md
This PR fixes an incorrect link on the "Theme Configuration" page.  The current link is redirecting to `/docs/padding` rather than going directly to `/docs/customizing-spacing`.
=> Fix broken link to spacing customization page

source/docs/configuring-variants.blade.md, source/docs/opacity.blade.md
This documents the new variants introduced in v1.1.0 on the configuring variants page. I went with the following recommended order for variants:
```js
['responsive', 'group-hover', 'focus-within', 'first', 'last', 'odd', 'even', 'hover', 'focus', 'active', 'visited', 'disabled']
```
Let me know if you'd like these in a different order!
Additionally, this documents the new default variants for opacity, I thought this was related enough to include it in this PR.
=> Update variants docs

source/docs/theme.blade.md
Replaced links to the defaultConfig.stub.js#5 as the stubs folder doesn't exist on the Next branch, so I pointed the links to the master. Either that, or add in the stubs or remove the references to the default theme settings.
=> Fixed 404 link to default theme config

source/docs/configuration.blade.md
I guess this got left behind from the v1 migration.
=> Fixed backgroundColors typo

source/docs/installation.blade.md
The Ember entry is using an `h4` tag, and isn't visible in the sidebar
=> Fix 'Ember.js' entry indentation in installation page

navigation.php, source/docs/screen-readers.blade.md
I have copied the explanations from the release info.
Since there was no category screen readers would fit under, I added a new category named "Accessbility". 
Showing previews for the code examples didn't seem to make sense to me, especially for `.not-sr-only`. I opted to simply show the HTML code.
=> Add documentation for screen reader classes.

source/docs/pseudo-class-variants.blade.md
It was confusing for users discovering the docs. 
The HTML example uses `group-hover` on `textColor` utilities, but the configuration right below adds `group-hover` on `borderColor`, which is unrelated.
=> Update group-hover example

source/docs/box-shadow.blade.md
Making sure the example in the box shadow article are having trailing comma to match the existing articles.
=> Making box-shadow example for customized config consistent with others

source/docs/table-layout.blade.md
I think the title is pretty explanatory, but I ran into a typo and figured I'd fix it.
=> Fix small typo in table layout examples

source/docs/stroke-width.blade.md
Preview: https://deploy-preview-344--elated-stonebraker-70896a.netlify.com/docs/stroke-width
=> [1.2] Add example/usage for stroke width util

source/docs/grid-auto-flow.blade.md
The docs show the CSS values generated by `.grid-flow-col`, `.grid-flow-row-dense`, and `.grid-flow-col-dense` as `col`, `row-dense`, and `col-dense`, when they're actually `column`, `row dense`, and `column dense`.
Tailwind [generates that CSS correctly](https://github.com/tailwindcss/tailwindcss/blob/61e5ac5f98468decf453711bcfa9460752f1ba27/src/plugins/gridAutoFlow.js#L6-L8), it's just the docs that show the invalid values.
=> Update grid-auto-flow docs to show correct underlying CSS declarations

source/docs/border-width.blade.md
Border width docs are missing a word in the description
=> Adds missing word

source/docs/box-shadow.blade.md
The sample itself already includes it, it was only missing from the code block and description text.
=> Add shadow-xs to description and sample sourcecode

source/_purge-whitelist.blade.php
Looks like `leading-{size}` is currently purged from the CSS: https://tailwindcss.com/docs/line-height/#fixed-line-heights
I'm not seeing any `leading-{size}` in https://tailwindcss.com/assets/build/css/main.css?id=da35c01d0ae8bad54242
=> Add leading-{size} to purge whitelist

source/docs/grid-row.blade.md
I think this is a typo in the documentation. I tried to build with gridRowStartEnd option and it didn't work. Using gridRowEnd it worked.
=> Fix possible typo on grid doc

package-lock.json, package.json
This PR updates the site to use Tailwind v1.3.0 and thus updates all references to the color pallete to include the new `current` color.
=> Update to Tailwind v1.3.0

source/docs/pseudo-class-variants.blade.md
"does not all variants for all utilities" -> "does not include all variants for all utilities"
=> fix tiny typo in docs

source/docs/text-opacity.blade.md
Add a note to text-opacity docs mentioning inheritance limitation:
See: https://github.com/tailwindcss/tailwindcss/issues/1780
=> Note inheritance limitation of text-opacity

source/_assets/js/components/WorkflowAnimation.vue, source/docs/utility-first.blade.md
The current image violates license because it should be used for internal design mockups only:
https://uifaces.co/license
Updated the image to be sourced from Unsplash, which has a more permissive license:
https://unsplash.com/license
The image is also higher resolution.
=> Fix license violation of user image

source/docs/theme.blade.md
Remove the extra backtick for fixing layout disorder.
Before:
After:
=> Remove extra backtick

source/docs/transition-timing-function.blade.md
The examples given should have "ease-" removed from the name as they result in you having to use a class named ease-ease-in-expo.  This is very confusing when trying to refer to the docs to create custom timing functions.
=> Correct naming of values for TransitionTimingFunction

source/docs/theme.blade.md
`height` is duplicated on [Theme Configuration > Configuration reference](https://tailwindcss.com/docs/theme/#configuration-reference)
=> Remove duplicated `height` on "Theme Configuration"

source/docs/pseudo-class-variants.blade.md
There is a typo in the `odd` and `even` js code
I changed `borderWidth` to `backgroundColor`
=> fix the typo in the code section

source/docs/margin.blade.md
Since we're trying to keep the default tailwind configurations when add new custom negative margins, the docs should explain that we must be extend and not override.
=> Fixes how to add custom negative margins

source/components/forms.blade.md
Hi! I noticed an extra class in the forms documentation, this PR removed the extra one.
From this `flex items-center border-b border-b-2 border-teal-500 py-2`
To this `flex items-center border-b border-teal-500 py-2`
=> Deleting extra class

source/docs/box-shadow.blade.md
The `2xl` and `3xl` keys are invalid. I've also updated the values to the latest values in Tailwind: https://github.com/tailwindcss/tailwindcss/blob/a05233281623739af7ad1ceaede6b0bf82a900db/stubs/defaultConfig.stub.js#L191-L202
=> Fix `2xl` & `3xl` quotes and update other `boxShadow` values

source/_layouts/documentation.blade.php
Replaced `focus:outline-0` with `focus:outline-none` — `focus:outline-0` doesn’t actually do anything (nor is it a standard Tailwind CSS class). 👍
=> Replaced focus:outline-0 with focus:outline-none on the search bar

source/docs/grid-template-rows.blade.md
The `Responsive` section, in the Grid Template Rows docs, was talking about columns when it should be talking about rows.
=> Rename 'cols' to 'rows' in Row - Responsive

source/docs/border-color.blade.md, source/docs/border-opacity.blade.md
The explanation and code example of border-opacity seem to mention background where it should be border. Corrected this in this PR.
=> Fix mistake in border opacity explanation and example code

source/docs/configuration.blade.md, source/docs/installation.blade.md
The default `tailwind.config.js` has become outdated in the docs.
=> Update default `tailwind.config.js`

source/docs/theme.blade.md
An extra "`" go into the `width` row in the configuration reference, which affects the layout, so this removes it.
=> Fix `height` key in theme reference

source/docs/justify-content.blade.md
This PR closes #379. `justify-evenly` is already in Tailwind, but has been missing from the docs.
=> Add justify-evenly to the docs

source/docs/margin.blade.md
https://tailwindcss.com/docs/margin/#responsive
lg example incorrectly bumps up the left and right margin.
=> Responsive margin - lg example uses wrong mr-8

src/pages/docs/font-size.mdx
[very minor]
JS needs object keys starting with numbers to be wrapped in quotes. You can see that the syntax highlighting marks it in red on the site:
https://i.imgur.com/FSjQxva.png
=> Wrap object keys starting with number in quotes

src/pages/docs/upcoming-changes.mdx
"to removing the now" should be "to removing them now" I think.
=> typo "to removing the now"

src/utils/defaultVariantsConfig.js
The [default variants section of the documentation](https://tailwindcss.com/docs/configuring-variants#default-variants-reference) is invalid JS since the object members don't have commas between them. It adds an extra step when copying defaults into your own config to customize them. This PR adds the commas.
Thanks for Tailwind 🙌
=> Fix invalid Javascript in the variant defaults snippet

src/utils/stats.js
- Replace user facing unit of measurement K with kB (1000 bytes = 1 kB)
- Use 1000 bytes to a kilobyte for the `convertToKB` function
Implements the change that @adamwathan wanted at the end of the discussion at #509.
Supersedes #509
=> Divide by 1000 and use kB as unit of measurement

src/pages/docs/customizing-colors.mdx
I was a bit confused that the `default` key is special for class generation but not for theme function so I think a small note here could be useful
=> Add note for default key when using theme function

src/layouts/DocumentationLayout.js, src/pages/docs/font-variant-numeric.mdx, src/pages/docs/justify-items.mdx, src/pages/docs/justify-self.mdx, src/pages/docs/place-content.mdx, src/pages/docs/place-items.mdx, src/pages/docs/place-self.mdx
I implemented a basic documentation page for all `font-variant-numeric`.
I also tried to explain what each of them does because the current font stack (setup) does not enable us to provide previews for each variant. 
Furthermore I added 5 more documentation pages showing the new `grid alignment` utilities.
I hope I got everything in place and correct. 
Generally I think the basic structure is in place and this can be improved further.
So please feel free to change stuff and correct things if I made a mistake!
Thanks for all your great work, @adamwathan!
=> Added Font Variant Numeric and Grid Alignment Documentation (v1.8)

src/pages/docs/adding-new-utilities.mdx
The example in [Using a plugin](https://tailwindcss.com/docs/adding-new-utilities#using-a-plugin) is missing a dot, resulting in an error:
```sh
(9:0) Variant cannot be generated because selector contains no classes.
```
=> fix: :pencil2: Add missing dot in snippet

src/pages/docs/controlling-file-size.mdx
Links to the specific options which can be passed through to purgeCSS. Just saves a couple of minutes finding the right page in the docs.
=> Add link to PurgeCSS options reference in docs

src/pages/docs/place-items.mdx
While reading through the documentation of [place-items](https://tailwindcss.com/docs/place-items#end) I noticed that `place-items-start` was mentioned under the headline "End". It should be `place-items-end`.
The code sample is correct.
=> fix: mention place-items-end in the correct location

src/pages/docs/place-items.mdx
Fix minor spelling error in `Place Items` docs
Changed to:
=> Fix spelling in Place Items docs

src/pages/docs/installation.mdx
**EDIT:**
I've changed the pull request so that it includes a heading and version badge, I've also rebased this branch so it's fully up to date with current `master`. I've also decreased the heading level from `h3` to a `h4`.
---
- Add text documenting the `npx tailwindcss init -p` option that scaffolds a basic PostCSS config file
- Use heading + badge with Tailwind version
[TailwindCSS 1.7.4 ](https://github.com/tailwindlabs/tailwindcss/releases/tag/v1.7.4) has added the `npx tailwindcss init -p` option to scaffold a basic PostCSS config file. This is not yet documented somewhere on the website, the string `init -p` gives no hits on the current `master`.
I'm not sure what the best place for this change is... Should it be in the [Installation.mdx](https://github.com/tailwindlabs/tailwindcs …
=> Add tailwindcss init -p documentation

src/pages/docs/controlling-file-size.mdx
Prompted by https://github.com/tailwindlabs/tailwindcss/discussions/2708 which lead to realising we upgraded to PurgeCSS 3 but didn't update the docs - this PR makes that update.
=> Change whitelist to safelist for PurgeCSS 3 options

src/pages/docs/plugins.mdx
Example was missing a comma, which led to a slight hiccup when attempting to copy and paste the example onto a project.
=> Add comma in example of addComponents multi-rule

src/pages/docs/installation.mdx
The section titled «Using Tailwind without PostCSS» has `post-css` and not `postcss` in the [working link](https://tailwindcss.com/docs/installation#using-tailwind-without-post-css) to section `#using-tailwind-without-post-css`.
=> Fix broken link to section

src/pages/docs/installation.mdx
Camel Case in the headers are changed to kebab case anchor links. This link needs the extra dash to work.
=> Fix broken link

src/components/home/ConstraintBased.js
Changed the key for default boxShadow to be uppercased in the shadow example so it uses the correct key from the default config.
**Before**
**After**
=> Use correct casing for boxShadows default key

src/pages/docs/gap.mdx
The number of columns was wrong in the class to compare to the template.
=> Fix column number in gap docs

src/pages/docs/ring-offset-width.mdx
`plugin="ringWidth"` => `plugin="ringOffsetWidth"`
Fix #614
=> Fix typo (tailwindcss.com#614)

src/pages/docs/grid-row.mdx
Just missing end tag for div in grid-row docs
=> Fix closing div tag in grid-row docs

src/pages/docs/hover-focus-and-other-states.mdx
A `button` in the docs demonstrating the disabled state has the `disabled` attribute twice.
=> Remove duplicated disabled attribute

src/pages/docs/top-right-bottom-left.mdx
It would be easier to understand the examples if the numbers (1 to 9) could match the ones in the code samples (1 or empty)
=> Fix the code sample's indexes to match the example

src/pages/docs/responsive-design.mdx
The example uses the class `md:w-48` but the description says `md:w-56`
=> Small descrepancy in "Responsive Design" docs

src/pages/docs/background-clip.mdx
Spend around 20 minutes figuring out why the snippet [here](https://tailwindcss.com/docs/background-clip#cropping-to-text) didn't work on my project until I realised that `teal` isn't a default colour anymore. IMO it makes more sense to use the default colours in the examples to avoid such confusion.
=> Use green instead of (non default) teal colour in text gradient example

src/pages/docs/box-shadow.mdx
Removed in Tailwind 2: https://tailwindcss.com/docs/upgrading-to-v2#replace-shadow-outline-and-shadow-xs-with-ring-utilities
Did not mention the ring utilities in this PR, though perhaps that could be a good idea as well.
=> box-shadow: Remove mentions of "xs"

src/pages/docs/overflow.mdx
Adds inline-block to the paragraph, so the right-hand-side is correctly padded
=> Fix horizontal scrolling on the overflow examples

src/pages/docs/overflow.mdx
In the examples:
https://tailwindcss.com/docs/overflow#scroll-horizontally-always
and
https://tailwindcss.com/docs/overflow#scroll-vertically-always
They don't really show the difference between "if needed" and "always" because the text is so tall or wide as to make scroll bars always needed. This change shortens the text so it's clearer in the always case that the scroll bars show up when not needed.
=> Update overflow scroll examples to better highlight the expected behaviour

src/pages/docs/justify-items.mdx
This docs page has a few duplicate `<div>` tags that don't need to be there.
=> Update Justify Items example to remove duplicate lines

src/components/VersionSwitcher.js
The top-right version drop-down on https://v1.tailwindcss.com doesn't include v2.0.
This PR fixed it.
Thanks.
=> Added v2 link to the VersionSwitcher

remark/withPrevalInstructions.js, src/pages/docs/installation.mdx
Yarn can correctly use the latest version automatically. For some reason
NPM itself can't, even after running `npm cache clean --force`, which
should clean the cache. It's a bit unfortunate to include this extra
bloat, but what can you do...
Fixes: #675
=> ensure that we include the `@latest` tags

src/pages/docs/hover-focus-and-other-states.mdx
In the example for the checkbox background- and border color are used.
However, only the background color variant is extended. So if you copy the example checkbox input and the config, the transparent border won't work.
By adding the border variant the `checked:border-transparent` will work.
There was also a bit confusion in the Discord, that's why I created this pull request.
=> Add border variant to checked example

src/pages/docs/controlling-file-size.mdx
_PurgeCSS 3.x_ has been released. Some _PurgeCSS_ options used by _Tailwind 1.8.x_ has been removed since _version 3.x_. I changed the documentation link to _version 2.x_ to avoid user confusion.
=> Change PurgeCSS Documentation URL

tailwind.config.js
Currently the docs scroll to fragment targets such as https://tailwindcss.com/docs/overflow#visible using the `scroll-margin-block` property to avoid the fixed top search bar. This is not supported in Safari.
The `scroll-margin-top` property is supported in Safari TP (and other browsers), so will likely be in the next release of Safari (https://bugs.webkit.org/show_bug.cgi?id=189265#c12).
This change switches to using `scroll-margin-top` to support future Safari and continue supporting Chrome/Edge/Firefox.
=> Modify scroll margin snap rule to better support future Safari

src/pages/docs/guides/nextjs.mdx
match next.js `globals.css` also mentioned in this guide
=> fix typo: update `global.css` to `globals.css`

src/pages/docs/box-shadow.mdx, src/pages/docs/dark-mode.mdx
the import for the `Heading` component was missing, resulting in a _funky_ HTML output for the `<Headline hidden>` component 😅
Fixes https://github.com/tailwindlabs/tailwindcss.com/issues/680
=> Fix broken heading anchor in dark mode docs page

src/pages/docs/top-right-bottom-left.mdx
In https://tailwindcss.com/docs/top-right-bottom-left, the classes in the top-right-bottom-left demonstration do not match the classes in the example code.
Setting the width for inset-x elements would not create the "span edge" effect.
=> Fix classes in inset-x example code

src/pages/docs/flex.mdx
Hi! Just a quick fix that I noticed while browsing the documentation. I updated the example code block to indicate that flex-none items will not grow or shrink.
=> Update HTML comment in 'flex-none' example block

src/pages/docs/adding-new-utilities.mdx
In Dark Mode section, fix to refer dark mode docs, instead of responsive design docs.
=> Fix to refer dark mode docs

src/pages/docs/background-image.mdx, src/pages/docs/gradient-color-stops.mdx
This is basically an extension of #625 where I spent an embarrassingly long amount of time trying to figure out why the code examples weren't working for me and it was because both teal and orange aren't default colors anymore.
=> Use default colors in gradient examples (teal -> green, orange -> yellow)

src/pages/docs/guides/vue-3-vite.mdx
- Vite scaffolding package changed
- Vite 2 uses postcss 8 by default
- Vite 2 has temporarily stopped using constructed stylesheets so the chrome fix is not needed
- Vite 2's Vue template no longer has the `src/index.css` so it needs to be created
Notably since, Vite 2 is now framework agnostic so maybe this can also be refactored into a more generic "Vite + X" guide.
=> Update Vue 3 + Vite guide

src/pages/docs/animation.mdx
As in the example, pings tend to be used on interactive buttons etc. Disabling pointer events means that the ping won't interfere with those buttons.
=> Add pointer-events-none to ping examples so they don't overlay the buttons underneath

src/pages/docs/installation.mdx
Fixes the anchor to _Installing Tailwind CSS as a PostCSS plugin_ from the _Using Tailwind via CDN_ section.
=> Fix PostCSS installation anchor

src/pages/docs/position.mdx
Remove this tip from the docs:
> Note that sticky positioning is not supported in IE11.
There's no point in keeping this since Internet Explorer is not supported anymore.
=> Remove IE11 tip

src/pages/docs/animation.mdx, src/pages/docs/transition-property.mdx
Hi! 👋🏽 
Just a small fix to a couple of links.
=> docs: remove version from motion-safe link

src/pages/docs/preflight.mdx
I'm not sure if I worded this the best way, but the removal of styles from `<ul>` and `<li>` elements has an unexpected side effect, which is that VoiceOver stops treating the content like a list. People using Tailwind need to be mindful of this and I'm hoping a note in the docs will help.
=> Add accessibility note about unstyled lists

src/pages/docs/order.mdx
Looks like `order-1`, `order-2` work with the grid ordering. Found this by trial and error so maybe a note in the docs will help?
=> Update order.mdx with grid

src/components/Search.js
Hello there Tailwind crew. 👋
Noticed that the search bar has no focus indication on the homepage, so I added the `focus:shadow-outline` to the `isHome` version since the over one does have a focus indication with the changing of the background and border color. 🙂
=> Add focus outline to homepage search variant

src/pages/docs/plugins.mdx
Small typo I noticed while browsing the docs
=> Fix typo in `plugins.mdx` example code block

src/pages/docs/configuration.mdx, src/pages/docs/hover-focus-and-other-states.mdx, src/pages/docs/installation.mdx
Hello,
I found that the tailwind documentation was using what appears to be outdated or a deprecated `postcss.config.js` .
I'm happy to make any changes and feel free to close if this isn't relevant.
Expected:
```
// postcss.config.js
module.exports = {
plugins: [
require('tailwindcss'),
require('autoprefixer'),
]
}
```
Actual:
```
// postcss.config.js
module.exports = {
plugins: {
tailwindcss: {},
autoprefixer: {},
}
}
```
=> Update postcss.config.js to use array for plugins

src/pages/docs/overflow.mdx
Small typo I noticed while browsing the docs. Thanks for the awesome work on Tailwind CSS!
=> Fix typo in overflow.mdx example code block

src/pages/docs/configuration.mdx, src/pages/docs/hover-focus-and-other-states.mdx, src/pages/docs/installation.mdx
Going to revert this for now because our own `tailwindcss init -p` command uses the object syntax, and the array syntax with `require` doesn't work in Next.js. Going to continue recommending object syntax for now, we can switch to the array syntax that uses tuples in the future instead if we can verify it's well supported by tools that integrate PostCSS out of the box.
=> Revert "Update postcss.config.js to use array for plugins"

src/pages/docs/guides/laravel.mdx
After the latest Laravel docs update, the link to the Laravel Installer section has been changed.
=> Fix Laravel Installer link

src/pages/docs/customizing-colors.mdx
[What is] This fixes a mistake about of the documentation about excluding colors.
[Issue] https://github.com/tailwindlabs/tailwindcss.com/issues/751
[URL] https://tailwindcss.com/docs/customizing-colors#disabling-a-default-color
[Photo]
=> fix(docs): delete Pink in customizing-colors (ISSUE: #751)

src/layouts/SidebarLayout.js
[What is] Remove `opacity-50` when item is selected in SidebarLayout because the contrast is poor.
[Issue] #744
[URL] https://tailwindcss.com, when item is selected in Sidebar
=> fix(docs): delete 'opacity-50' in items SidebarLayout.js (ISSUE: #744)

src/pages/docs/animation.mdx
Unlike other classes in the documentation, classes for animation had dots in the names. This PR removes the dots.
=> Remove dots from animation classes

src/pages/docs/gradient-color-stops.mdx
Hi!
I just hit this bug on iOS for the 1000th time in my career and all because I had the good intention of writing concisely "to-transparent" where I wanted my gradients to fade to transparent. After analyzing Tailwind's gradients code, I had a POG moment seeing that the fade to the correct transparency with rgba was default. I read this documentation page multiple times before, but didn't notice that it was mentioned and didn't realize it was also to prevent this iOS bug (be it willingly or not). So I thought adding a little more details couldn't hurt. 
Feel free to reject or reword! 🔥
=> Adding notes about the fade to transparency

src/pages/docs/guides/nextjs.mdx
This is a small change.
Basically, the coding style used in Next.js by default (and in the guide) is to use single quotes and without semicolons. The added import from the guide instructions is:
```js
import "tailwindcss/tailwind.css";
```
But, for consistency with the rest of the docs, it should be:
```js
import 'tailwindcss/tailwind.css'
```
=> Fix line in Next.js guide for coding style consistency

src/pages/docs/just-in-time-mode.mdx
This PR fixes an issue mentioned here: https://github.com/tailwindlabs/tailwindcss/issues/3977
=> Fix: Add dot (.) in example commands

src/pages/docs/ring-offset-color.mdx, src/pages/docs/ring-offset-width.mdx
Ring CSS variables are now using a 'tw-' prefix.
Affected pages:
- https://tailwindcss.com/docs/ring-offset-width
- https://tailwindcss.com/docs/ring-offset-color
=> Fixed CSS variable names

src/pages/docs/responsive-design.mdx
If html font-size up to 200% (accessibility test) then image should be full hight.
=> Feat md:card preview to full hight

src/components/Tip.js
`class` is a keyword in javascript and JSX.
React uses `className` instead of `class`.
=> Use "className" instead of "class"

src/pages/docs/hover-focus-and-other-states.mdx
Change `translate` key in extend variants section to `animation`
=> fix docs typo in `motion-reduce` and `motion-safe`

next.config.js, rehype/withLinkRoles.js
Hey there! I have a little screen reader fix for you! The [preflight docs mention that the margin reset prevents VoiceOver from announcing lists properly](https://tailwindcss.com/docs/preflight#accessibility-considerations). The workaround there is really nice and I thought it was worth applying to all the markdown lists in the docs, since those are all true lists from a semantic point-of-view and should have the standard screen reader list UX.
Here's an example of the impact of this change using what I'd consider one of the most important parts of the Tailwind docs: [the part that explains the value proposition of utility first CSS](https://tailwindcss.com/docs/utility-first). To a screen reader user, this section reads like 5 separate paragraphs because the semantic list association …
=> Add role="list" to all markdown lists

src/pages/docs/whitespace.mdx
There are some formatting issues on the Whitespace page, that are visible in the "Pre Wrap" section here:
https://tailwindcss.com/docs/whitespace#pre-wrap
This PR adds some missing closing tags, which I think will fix those formatting issues.
=> Add missing closing tags to Whitespace page

src/components/Logo.js
The Tailwind logo is cut off at the right on Firefox.
This commit fixes this issue by increasing the logo's viewBox width by 1.
=> Fix logo being cut off on Firefox

src/pages/docs/grid-auto-flow.mdx
I'm fairly certain this is a mistake, because from what I understand, this would actually not do anything if both were there?
=> Remove duplicate class from docs

src/layouts/ContentsLayout.js
This is a quick and (hopefully not so) dirty addition.
A link to edit the current documentation page on GitHub – between content and prev/next links.
**Suggestion:**
Import the GitHub icon as component or remove it. The inline SVG is used multiple times now.
Closes #821 (not)
🖖
=> Add link to quickly edit docs pages on GitHub

src/pages/docs/max-width.mdx
Clarify that the `max-width-screen-*` classes use the themen.screen configuration.
We changed our themen.screens settings last week and lost some max-width-screen-* classes due to this change which I was not aware of and did not find any reference about in the docs. This PRs is an attempt to clarify the secondary source of values (not only the size-, but also the screen-values are used).
I understand this PR more as an github-issue with some pointer to where I was missing information. If it's also something that can be merged, all the better; otherwise please treat it as an issue with a problem description and suggestion.
=> MaxWidth-Section: Clarify `max-width-screen-*`

src/pages/docs/guides/nextjs.mdx
While reviewing [this PR](https://github.com/vercel/next.js/pull/22964), I realized the docs should suggest using the official example as they're [now identical](https://github.com/vercel/next.js/pull/19750).
Let me know if the format of the PR is correct (wasn't sure with the preval stuff). Thanks!
=> Update Next.js <> Tailwind guide.

src/pages/docs/guides/nuxtjs.mdx
https://tailwindcss.nuxtjs.org/setup nuxt.js/tailwindcss no longer depend on Postcss-7.
=> Update Nuxt postcss compatiblity

src/pages/docs/configuration.mdx
It took me 1 day of experiments to understand why purging is removing all my utilities. 😄 
My use case is that I have a library of Vue components and Storybook.
And the `important` selector was in `.storybook/preview-body.html`
```html
<body class="ui-root"></body>
```
I had to update purge in `tailwind.config.js`
```js
{
important: '.ui-root',
purge: {
content: [
/**
* When using `important` option in Tailwind you need also to tell purge the file
* where this selector is contained
*/
'./.storybook/preview-body.html',
'./src/**/*.js',
'./src/**/*.ts',
'./src/**/*.vue',
],
},
}
```
=> Add note about purging important selector

src/pages/docs/index.js
This PR adds a link to the Tailwind CSS 2.2 blog post in the latest updates timeline from the `/docs` page
=> Link to Tailwind CSS 2.2 blog post in Latest Updates

src/pages/docs/hover-focus-and-other-states.mdx
See https://github.com/tailwindlabs/tailwindcss/issues/4204 (Adam said that he already updated the docs, but I don't see it here. Maybe it was in another place.)
When I first tried the example code, I didn't understand why the focus ring was still showing when I clicked the button with the mouse. I thought that using `focus-visible` alone would only show the ring when using the keyboard. It's only when inspecting the source code that I understood that `focus:outline-none` was necessary (which on a second thought makes perfect sense).
=> Add focus:outline-none to example code for focus-visible

src/pages/docs/guides/nextjs.mdx
Add "or newer" to the line mentioning the latest Next.js instructions, this way it's clear you can use Next.js 11
=> Update guide for Next.js 11

src/pages/docs/guides/vue-3-vite.mdx
I just noticed that `@vitejs/app` is deprecated now and we should use `npm init vite` instead of that. So I updated the docs accordingly
=> Changed @vitejs/app to vite as per the latest changes

src/pages/docs/font-family.mdx
This is a minor change to add quotes to a multi-word font name in the documentation around font families. This double quote requirement is mentioned in the section below.
=> Add required quotes to font name in example

src/pages/docs/animation.mdx
I think the CSS Property should be renamed to `animation-timing-function` in the docs regarding the MDN Web documentation:
https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function
=> Rename animation timing function

src/pages/docs/space.mdx
It is not possible to use `space-*` and `divide-*` together in a sensible ways which is a limitation that is well fitted to be part of the docs.
Ping https://github.com/tailwindlabs/tailwindcss/discussions/2466
=> Extend limitations for space utils about divide

src/pages/docs/just-in-time-mode.mdx
Fixes a typo in the docs, where the code comment references black color even though `bg-blue-500` is the class that's being used.
=> Fix a typo: black -> blue

src/pages/docs/just-in-time-mode.mdx
A closing tag for the `<span>` in the example for the peer classes was missing which resulted in incorrect HTML.
=> Add closing span tag to peer classes example

src/pages/docs/extracting-components.mdx
Updates Laravel documentation link to the latest stable version in `docs/extracting-components.mdx`.
=> docs: update Laravel doc link

src/pages/docs/guides/gatsby.mdx
The old link's anchor is no longer relevant. This change points to a more relevant entry in Gatsby documentation.
=> Fix link to Gatsby global style guide

src/pages/docs/plugins.mdx
This PR fixes a typo in the Tailwind docs for plugins that I just stumbled upon.
The generated class names are all ending in `-blue` where the latter two should be named `-red`.
=> Fix typo in generated code for plugins docs

src/pages/docs/responsive-design.mdx
The current example has `bg-teal-500` but it looks like `teal` doesn't exist in the color palette for the latest version (2.2.14) of tailwindcss https://tailwindcss.com/docs/customizing-colors.
=> Updating color for breakpoint example

src/pages/docs/background-image.mdx
The usage of the arrow function syntax (`theme => ({ })`) in the code sample here is confusing because it suggests that the `theme` argument will be used elsewhere in the snippet, but it is not.
=> remove extraneous arrow fn syntax from backgroundImage code sample

src/components/ClassTable.js
When we have a class like `.inset-1\/4` we want it to look like
`inset-1/4`. We used to remove the first character, but that is not
correct. Some classes are structured like `*, ::before, ::after {}`.
Instead we now drop leading `.` characters instead.
=> Improve rendering of classes

src/pages/docs/list-style-position.mdx
Clarify that the utility classes not only change the position of the marker, but also how text indentation works.
The third list element is now multi line, so the effect becomes visible. And the intro sentence hints that this util changes more than just the position.
Pages: 
- Current: https://tailwindcss.com/docs/list-style-position
- This PR: https://tailwindcss-com-git-fork-tordans-patch-2-tailwindlabs.vercel.app/docs/list-style-position
See also https://github.com/tailwindlabs/tailwindcss/issues/4549 by @jpwynn 
Personally, I would even go a step further, and reverse the order of utils (currently (1) inside, (2) outside). This nudged me towards the inside option being the smarter choice, but TBH I don't see when that would be true – unless you can be sure that your list will never get …
=> list-style-position: Clarify and illustrate the different text indentation behavior of list-inside vs. list-outside

src/pages/docs/plugins.mdx
Minor fix to "supports-grid" plugin example to avoid multiple escapes of content in `${rule.selector.slice(1)}`.
**Example**:
`class="supports-grid:hover:underline"`
Before:
```
@supports (display: grid) {
.supports-grid\:hover\\\:underline\:hover {
text-decoration: underline;
}
}
```
After:
```
@supports (display: grid) {
.supports-grid\:hover\:underline:hover {
text-decoration: underline;
}
}
```
=> Fix multiple escapes in plugin code example

src/components/Tip.js
Minor patch to fix the SVG clipping by adding a `viewBox` to the SVGs to the `TipGood` and `TipBad` components. Example page: https://tailwindcss.com/docs/responsive-design#mobile-first
**Before** 
**After**
=> Tip Component: Add viewBox to SVGs to fix clipping

src/pages/docs/optimizing-for-production.mdx
* Add `important` selector strategy note to `purge`
- Use same wording from [`important` selector strategy section](https://tailwindcss.com/docs/configuration#selector-strategy), with added "`important` with"
When I had problems with my `purge` not working as expected, the [Optimizing for Production > Basic Usage page](https://tailwindcss.com/docs/optimizing-for-production#basic-usage) is the page I came to. I solved my problem because I saw this [issue](https://github.com/tailwindlabs/tailwindcss/issues/1924), and I completely missed the note in the [Configuration > Selector Strategy](https://tailwindcss.com/docs/configuration#selector-strategy) section.
=> Add `important` selector strategy note to `purge`

src/pages/docs/just-in-time-mode.mdx
In https://youtu.be/oG6XPy1t1KA?t=995 I learned about the `--minify` option.
Minifying the output sounds like a smart default for `build` scripts.
However, I could not find any reference to it in the docs, yet. So this adds it to the examples at least.
I suggest also adding a list of all option values or link to an external list if there is one.
---
Update: I found the reference to minify in the CLI section at https://tailwindcss.com/docs/installation#building-for-production. I still think a list of all cli options and also using this specific option on this page is a good idea. 
---
This PR also changes the IMO cryptic `-w` in favor `--watch`.
=> Add `--minify` to just-in-time-mode.mdx

src/pages/docs/plugins.mdx
This change is to remove an invalid bracket from one of the plugin code examples
=> Remove incorrect bracket from plugin code example

src/pages/docs/guides/nuxtjs.js
Found a typo in the Nuxt guide. This PR fixes that typo.
=> Fix: Change tailwind.css to main.css

src/pages/docs/hover-focus-and-other-states.mdx
Noticed that the valid/invalid variants were copied from required and weren't changed.
=> Fixing valid/invalid variant docs

src/pages/docs/hover-focus-and-other-states.mdx
`marker:text-sky-400` is duplicated in the same element:
`<ul role="list" class="**marker:text-sky-400** list-disc pl-5 space-y-3 text-gray-500 marker:text-sky-400">`
Output generated HTML Code is:
```HTML
<ul role="list" class="marker:text-sky-400 list-disc pl-5 space-y-3 text-gray-500 marker:text-sky-400">
<li>5 cups chopped Porcini mushrooms</li>
<li>1/2 cup of olive oil</li>
<li>3lb of celery</li>
</ul>
```
And since you can select the first(Highlighted) for copy and paste without the highlight formatting, there's no need for the last class.
https://user-images.githubusercontent.com/79575415/145547786-9ec39a0b-c2b4-46c6-8950-692f5cd6a490.mp4
=> Remove duplicated class in List markers example

src/pages/docs/adding-custom-styles.mdx
Original Sentence (with typo):
> By defining component classes in the `components` layer, you can still user utility classes to override them when necessary:
Changed "user" to "use".
=> Fix a typo in the docs

src/pages/docs/line-height.mdx
This PR fixes an inconsistency between the documentation text and its corresponding snippet of code.
The relative line-height had an example for fixed-line heights.
=> Fix: Relative line-heights html code snippet

src/pages/docs/guides/create-react-app.js
I was stuck on an issue for about an hour where my typescript files weren't getting styles and this was the culprit. It's a little obvious and I should have seen it coming, but mentioning it in the docs might help the next person using typescript and trying to add tailwind.
=> Add ts,tsx to guides/create-react-app.js

src/pages/docs/rotate.mdx
changed "Basic _sage" to "Basic usage"
=> Corrected spelling on Rotate.mdx

src/pages/docs/hover-focus-and-other-states.mdx
In the [Open/closed state](https://tailwindcss.com/docs/hover-focus-and-other-states#open-closed-state) The `summary` text is almost invisible while in closed state with Dark mode. 
Current view:
Added some `dark:` utilities so it can work with Dark mode.
=> Fixed "Open/closed state example" with Dark Mode

src/pages/docs/using-with-preprocessors.mdx
The example used to install `postcss-import` should install it as a dev dependency
=> Update postcss-import example

src/pages/docs/content-configuration.mdx
I think it will be good if we describe that each responsive variant must be specified in the array.
=> Docs: Add example to safelist responsive variants

src/pages/docs/hover-focus-and-other-states.mdx
The anchor link for `file` on the [states quick reference](https://tailwindcss.com/docs/hover-focus-and-other-states#quick-reference) is wrong.
It points to [#file](https://tailwindcss.com/docs/hover-focus-and-other-states#file) which is wrong.
[#file-input-buttons](https://tailwindcss.com/docs/hover-focus-and-other-states#file-input-buttons) works
=> Fix anchor link for file quick-reference

src/pages/docs/optimizing-for-production.mdx
This PR fixes a tiny inconsistency between the documentation text and its corresponding snippet of code. 
The `safelist` option should live under the `purge` option, not in the top-level configuration.
=> Fix reference to safelist option as top-level configuration

src/pages/docs/functions-and-directives.mdx
This small PR removes a broken link from the functions and directives page. It looks like the `#nested-object-syntax` section on the colors page isn't present in the v3.0 docs, breaking this link.
=> Remove broken link from functions and directives

src/pages/docs/optimizing-for-production.mdx
This PR adds the missing "process.env" for the optimizing section.
=> Fixes typo by adding the missing 'process.env'

src/pages/docs/flex-basis.mdx
The `flex-basis-[14.2857143%]` won't work, it should be `basis-[14.2857143%]`.
=> Update docs for Flex Basis chapter

public/img/cursors/cursor-none.svg, src/pages/docs/cursor.mdx
This tiny PR is a one-file change which fixes the `cursor-none` image example—it’s currently displaying as `not-allowed` instead of nothing.
=> Fix: Docs `cursor-none` image

src/pages/docs/installation/play-cdn.js
From discussion https://github.com/tailwindlabs/tailwindcss/discussions/6473
Reference core plugins in last section as option to extend functionality
=> Add core plugins reference in PlayCDN

src/pages/docs/transition-duration.mdx
The `duration` docs currently display `transition-[2000ms]` as an example of an arbitrary value for the `duration` class.
=> Fix class name for arbitrary duration values

src/pages/docs/presets.mdx
Small fix to update **purge** to **content** at https://tailwindcss.com/docs/presets#merging-logic-in-depth.
=> fix: renaming purge to content on presets doc

src/pages/docs/grid-template-columns.mdx
the arbitrary values should not be working if the class list doesn't contain a grid class. To avoid confusion a defaultClass="grid" should help mitigate the problem.
=> 📝defaultClass to grid-template-columns arbitrary values

src/pages/docs/guides/create-react-app.js
Create React App's Tailwind support means that they will detect `tailwind.config.js` in the project and add `tailwindcss` to their existing `postcss` configuration. [Source in CRA](https://github.com/facebook/create-react-app/blob/5614c87bfbaae0ce52ac15aedd2cd0f91ffd420d/packages/react-scripts/config/webpack.config.js#L144)
The [guide](https://tailwindcss.com/docs/guides/create-react-app) that Tailwind offers on their site creates a dummy `postcss.config.js` - Making changes in this file does not change the actual postcss configuration. (misleading if anything)
This means that features like PostCSS Nesting that Tailwind mentions in the docs will not work if user edits the local PostCSS configuration. It should be better to simply *not* create `postcss.config.js` in the first place so that …
=> Remove instruction to create postcss plugin when using CRA

tailwind.config.js
Block quotes in `prose-dark` uses `prose-slate`'s color which is too dark to see in dark mode
Resolves #1197
=> added white color for blockQuote in dark prose theme

src/pages/docs/upgrade-guide.mdx
This commit adds a missing description on how to migrate to Tailwind v3 if you're using PostCSS config with nesting enabled.
=> Add a note about PostCSS config migration

src/pages/docs/hover-focus-and-other-states.mdx
This change adds a missing space between the `bg-white` and `ring-1` classes in the "Styling based on parent state" example.
=> Add missing space

src/pages/docs/guides/parcel.js
[Parcel v2.4.0](https://parceljs.org/blog/v2-4-0/) now uses [@parcel/css](https://github.com/parcel-bundler/parcel-css) by default for auto prefixing and transpilation (like postcss-preset-env). It shows a warning telling users to remove `autoprefixer` from their postcss config file, which is now redundant with the builtin auto prefixing support and can improve performance.
Unfortunately, it looks like the `tailwindcss`CLI doesn't have a way to skip autoprefixer when generating a postcss config, so I removed the `-p` option and created the postcss config containing only `tailwindcss` manually in these instructions for now.
It also seems that `autoprefixer` is a peer dependency of `tailwindcss`, and you do get a warning during install when it isn't added. Maybe that could be made optional …
=> Remove autoprefixer from Parcel installation guide

src/pages/docs/gradient-color-stops.mdx
Since the bug has been fixed in Safari 15.4, I thought we could add these little changes since the bug has been closed and shipped by the Webkit team. I just specified that it's up to 15.3 and solved in 15.4, but we could eventually think about removing this section altogether. Your call!
=> Fading to transparent - Fixed in 15.4 note

package.json, src/components/ThemeToggle.js, yarn.lock
This PR fixes theme toggle state sync. When updating the theme setting (`light`, `dark`, or `system`) on mobile the desktop version of the toggle will now be updated correctly, and vice versa.
=> Fix mobile/desktop theme toggle sync

src/components/HtmlZenGarden.js, src/components/Steps.js, src/components/home/BuildAnything.js, src/components/home/ModernFeatures.js, src/components/home/ReadyMadeComponents.js, src/samples/build-anything.html, src/samples/dark-mode.html, src/samples/editor-tools.html, src/samples/filters.html, src/samples/grid.html, src/samples/transforms.html
Hey TailwindLabs,
I started a personal project where I'm trying to make 100 page performance-related contributions to the projects I use and love.
TailwindCSS is one of these projects, and also the first one I've choosen to start my project with.
I've noticed that the Core Web Vitals are failing for the homepage, so I found some low-hanging fruits to start fixing these issues.
I've updated the code loading the images + the code samples to reflect the changes I've introduced to the components you feature on the homepage.
I managed to delay 1MB of images that weren't used on the first load.
Here are the "before stats" (Localhost, focus was on the IMG tab from the Chrome Dev Tools):
Here are the "after stats":
=> Improve homepage performance by lazy loading images

src/pages/docs/guides/remix.js
The Remix guide does not have the `--postcss` flag to load the PostCSS configuration.
=> Fix: Load custom PostCSS configuration

src/components/Search.js
The `onInput` parameter is not used in the `useDocSearchKeyboardEvents` hook.
=> Remove extra `onInput` parameter

src/pages/docs/guides/sveltekit.js
The CSS grammar allows any characters that are not `;` or `{` as part of an at-rule "preamble" but Svelte's CSS parsing breaks on at-rules containing a `:` when nested inside rules. This situation occurs when user's apply classes with variants, for example, `@apply dark:bg-white`. To combat this we need to add `svelte-preprocess` and configure it run postcss on `<style>` blocks before svelte has a chance to analyze the CSS. It'd be great to not need this but, at least for now, we do.
Fixes #1221
=> Update SvelteKit guide

src/pages/docs/dark-mode.mdx
In the example that is being displayed the `bg-slate-800` class is used, see line 34.
However, the provided code snippet used `bg-slate-900`, see line 52.
=> Fixed typo: example code using wrong color class

src/pages/docs/hover-focus-and-other-states.mdx
On the **["First, last, odd and even"](https://tailwindcss.com/docs/hover-focus-and-other-states#first-last-odd-and-even)** section the table code being shown as an example mentions the use of `bg-slate-100,` but the actual color being used is `bg-slate-50`. I detected this error because the color on my code looked different.
=> Update even:bg color for table example

src/pages/docs/customizing-colors.mdx
In the example primary was listed a second time instead of secondary.
=> Fixed typo

src/pages/docs/hover-focus-and-other-states.mdx
In "spaces in selector" part the generated css was mistakenly took from a previous example.
=> fix: generated CSS mismatches with example

src/pages/docs/border-width.mdx
For consistency among utility names. There was a missing dot (.)
🔬😅,
=> Micro typo

src/pages/docs/guides/laravel.js
`npm run watch` is not defined in Laravel's npm scripts so it should be `npm run dev`.
=> Fixed wrong command in Laravel guide.

src/pages/docs/plugins.mdx
I was looking at the example and was wondering if `prefix` should be documented.
As I learned from [this](https://github.com/tailwindlabs/tailwindcss/pull/8770#issuecomment-1173984577) comment, `prefix` is deprecated and should be removed from the documentation.
=> Remove `prefix` from plugin api example

src/pages/docs/hover-focus-and-other-states.mdx
The comments explained a different color than was used in the demonstration. I've changed the comment to say the correct color.
=> match comment color to demo color

src/pages/docs/content-configuration.mdx
Hi, 
In this PR, I'm adding the title Class names so it is easier to share a direct link to the documentation about Tailwind extracting class names and why we should not use string interpolation or concatenate partial names.
=> feat: add heading to class names extraction

src/pages/docs/hover-focus-and-other-states.mdx
Rendering `bg-sky-500` but showing `bg-sky-600` and `bg-sky-700` in the documentation
=> fix: generated CSS mismatches with HTML

src/pages/docs/guides/sveltekit.js
SvelteKit recently introduced changes to the its router ([among others](https://github.com/sveltejs/kit/discussions/5774)): The `__layout.svelte` file is now named `+layout.svelte`, and `index.svelte` → `+page.svelte`. This PR changes those two file names so the installation guide is up-to-date again.
See here for a complete overview of the filename changes: https://github.com/sveltejs/kit/discussions/5774
=> Update SvelteKit installation guide

src/pages/docs/content-configuration.mdx
In a workspace setup encouraging people to directly path into `node_modules` will result in inconsistent outcomes. Instead rely on the system to properly identify the path of the node module, and then append the glob pattern manually.
This will result in a system-path-separator normalized absolute path which is distinct from the current `contents` items. I did not investigate if that will work as expected where these values are consumed so I wanted to draw attention to the distinction.
=> Guide people toward using path resolution.

src/pages/docs/adding-custom-styles.mdx
Hey everyone, I've [just learnt](https://twitter.com/adamwathan/status/1561370840415223808) that it's possible to use `theme()` within arbitrary values , and realised it wasn't mentioned in the docs, so I've added a quick example. 
There's a few use cases for it, I've used the top one in the code demo:
```
grid grid-cols-[fit-content(theme(spacing.32))]
w-[calc(theme(screens.lg)/12)]
bg-[conic-gradient(theme(colors.green.400),black)]
```
See the generated CSS in [Tailwind Play](https://play.tailwindcss.com/Gr3fFYnumf)
=> Mention using theme() inside arbitrary values

src/components/ColorPaletteReference.js
I love tailwind's color palette in the docs and I've used it many times before as a color palette reference for my projects. One feature that I think will be useful is this one. I think it will help people to copy the color code quicker.
Let me know if there's any suggestions and comments to improve this PR. Cheers! 🍻
**Light vs dark mode:**
https://user-images.githubusercontent.com/32460534/187025807-472d39fc-1b9d-41f7-bcf6-f04ca4b8b4a9.mov
**Clicking on multiple colors quickly:**
https://user-images.githubusercontent.com/32460534/187026029-d3ee94fa-2833-43bd-947f-281f9833896e.mov
=> Copy color code to clipboard

src/pages/docs/guides/solidjs.js
Thanks for adding a SolidJS guide. The JSX example included in the last step uses the `className` attribute in the JSX. This is invalid SolidJS JSX syntax. We can just use `class` attribute directly here without any issue 😄
=> fix: SolidJS Example `className` attribute

src/pages/docs/configuration.mdx
Copy is taken from the press release for v3.1 https://tailwindcss.com/blog/tailwindcss-v3-1#first-party-type-script-types
=> Add docs about tailwind.config.js IDE type-hinting

src/pages/docs/overflow.mdx
Remove strange dots from Tailwind classes
I haven’t checked other files, so there might be more.
=> docs: fix typo

src/pages/docs/place-items.mdx
Corrects a typo on line 16: the plural of “axis” is “axes”.
=> Typo in `place-items.mdx`

src/pages/docs/guides/nextjs.js
The previous link points to an old version of the Next.js + Tailwind CSS Example. With this old version it is not possible to simply one click copy the commands for each package manager (npm, yarn and pnpm), therefore I updated the link to the current (Sep 2022) version.
=> Update link to Next.js + Tailwind CSS Example

src/pages/docs/presets.mdx
[`safelist` seems to follow the replacing logic](https://play.tailwindcss.com/mk3pUMOM6K?file=config) like other options, such as `darkMode`, `important`, etc. – let's be explicit here and let users know this!
=> State `safelist` is replaced in preset merging

src/pages/docs/font-size.mdx
Seems like the `font-size` documentation is missing information about the [`font-weight` option](https://github.com/tailwindlabs/tailwindcss/blob/27aee8fc29c48b34068c546d5384802fc09aa0ed/src/corePlugins.js#L1636-L1644) – could we consider adding it in?
Alternatively, with the increasing number of properties, would it be worth consolidating the `line-height`, `letter-spacing` and `font-weight` sections somehow?
=> Add default `font-weight` documentation to `font-size`

src/pages/docs/editor-setup.mdx
Added a section about the prettier-plugin-tailwindcss to the editor-setup page. Focused on keeping it short & concise and link to the repo and blog post for more details and instructions.
The reasoning behind adding this to the docs is based on the discussion here on Twitter: https://twitter.com/t3dotgg/status/1575334522056372225
=> Add prettier-plugin-tailwindcss to editor-setup

src/pages/docs/adding-custom-styles.mdx
When reading the section on `arbitrary variants` it is difficult to know that there are documents for `arbitrary variants`, which are very relevant. `arbitrary variants` are a little hidden, under a title that doesn't mention anything about CSS selectors, therefore this PR: Adds a link to the related content.
I added this right after `### Arbitrary properties` because it is almost as essential, and I added it before `### Handling whitespace` given that white space is a CSS selector and the order of question tends to be:
1. How do I add a custom selector?
2. How do I add the specific white space (descendant) selector?
=> Add arbitrary-variants section in arbitrary-values

src/pages/docs/hover-focus-and-other-states.mdx
This PR adds a new "Supports rules" section to the "Handling Hover, Focus, and Other States" page for the new `supports-[]` modifier coming in Tailwind CSS v3.2.
I added it to the end of the "Media queries" section, and renamed this section to "Media and feature queries".
I also added `supports-[…]` to the "Quick reference" section.
=> [v3.2] Add `supports-[]` modifier documentation

src/pages/docs/hover-focus-and-other-states.mdx
This PR adds a new "Data attributes" section to the "Handling Hover, Focus, and Other States" page for the new `data-[]` modifier coming in Tailwind CSS v3.2.
I added it to the "Attribute selectors" section. It should come after the new ARIA modifiers (#1391).
I also added it to the "Quick reference" section.
=> [v3.2] Add `data-*` modifier documentation

src/pages/docs/visibility.mdx
This PR adds docs for the new `collapse` utility coming to Tailwind CSS v3.2.
=> [v3.2] Add `collapse` documentation

src/pages/docs/font-family.mdx
This PR adds a new "Setting default font-feature-settings" section to the "Font Family" page explaining how to set default `font-feature-settings` for the fonts in your project using the new `fontFeatureSettings` option coming to Tailwind CSS v3.2.
=> [v3.2] Add default `font-feature-settings` documentation

src/pages/docs/hover-focus-and-other-states.mdx
This PR adds documentation for the `supports-foo` case where `foo` is coming from your
`tailwind.config.js` file.
Saved you a few clicks: https://tailwindcss-com-git-feat-document-supports-config-tailwindlabs.vercel.app/docs/hover-focus-and-other-states#supports-rules
=> [v3.2] Document `supports-foo` configuration

src/pages/docs/content-configuration.mdx
This PR documents the new `relative: true` content option coming to Tailwind CSS v3.2.
=> [v3.2] Add "Using relative paths" section to the "Content Configuration" page

src/pages/docs/configuration.mdx, src/pages/docs/functions-and-directives.mdx
This PR adds documentation for the new `@config` directive to the "Functions & Directives" and "Configuration" pages.
=> [v3.2] Add `@config` documentation

src/components/SnippetGroup.js
- initial version: remove focus styles completely
- only hide outline for mouse users
=> Improve focus outline styles — hide them for mouse users

src/pages/docs/guides/nextjs.js
Ensures tailwind is compatible with https://nextjs.org/blog/layouts-rfc when it becomes available.
=> Add `app` directory to content for Next.js

src/components/home/EditorTools.js
Fixes a 404 error for an image on the homepage:
---
Perhaps we could also consider adding `loading="lazy"` so the image is not requested at all in dark mode (since it has `dark:hidden` on it anyway)?
=> Fix 404 Editor Tools image

src/components/Guides/TabBar.jsx
Fixes illegible `<code>` tags in dark mode for inactive tabs used in the Framework Guides Installation section. Example, `/docs/guides/nextjs`:
=> Fix illegible guide tab bar code text in dark mode

package-lock.json, package.json, src/pages/docs/font-size.mdx
This PR adds documentation for the new line-height modifier for font-size utilities introduced in https://github.com/tailwindlabs/tailwindcss/pull/9875.
=> Document new line-height modifier

src/pages/docs/adding-custom-styles.mdx
This PR documents the new shorthand for using CSS variables as arbitrary values added in https://github.com/tailwindlabs/tailwindcss/pull/9880.
=> Document arbitrary variable shorthand

src/pages/docs/preflight.mdx
It should either be "the browser assigns" or "browsers assign", but in the context of highlighting that different browsers might have different behaviors, it makes sense to talk about it in plural.
=> Fixed spelling error in preflight.mdx

src/components/Steps.js
The bg image in `<Steps>` is blocking clicks to `<TabBar>`.
This pulls the bg image element to `z-index: -10` to prevent click blocking.
=> Fix bg image blocking tab nav

src/pages/docs/plugins.mdx
Follow up to #1434 with more comprehensive documentation. Notes:
- In 757e04d, I took the liberty of changing mention of the *active* built-in variant to *supports*, so that this unexhaustive list mentions a dynamic variant.
- In 0ea182b, I thought it would be necessary to change the at-rule example since supports is now a built-in (I have noticed this used in other places too but I presume that would be something for another time). I instead used a "boolean" `@media` rule since this would be the most likely candidate for `addVariant()`, as `@media` rules with more than two values would be more of a candidate for `matchVariant()` instead.
-  In 41c8672:
- I adapted the example of `matchVariant()` from the v3.2 release blog post, but attempted to use an example that had less context with …
=> Document `matchVariant()`

src/pages/docs/guides/sveltekit.js
We will soon be releasing SvelteKit 1.0. The `latest` tag will work now with the latest betas / RCs and will continue to work after 1.0. The `next` tag will only work until 1.0 is released
=> Update SvelteKit guide for 1.0

src/pages/docs/content-configuration.mdx
In these code examples, a comma is forgotten in the line that causes an error when executed.
=> The missed comma in the code example

src/pages/docs/guides/sveltekit.js
Remove missed `svelte-preprocess` mention in the explanation on how to install Tailwind CSS in a SvelteKit project. #1462
=> Update SvelteKit guide.

src/pages/docs/font-size.mdx
Font sizes greater than `xl` require to be wrapped in single quotes
=> Fix: add single quotes to code example in font sizes

src/pages/docs/guides/phoenix.js
In troubleshooting walking through the guide with a friend who is new to Phoenix, they had errantly added `"assets.deploy": ["tailwind default --minify", "esbuild default --minify", "phx.digest"]` below the existing alias. This had the effect of not building the expected `app.css` even though everything else was configured correctly.
I'm not a huge fan of how splitting this into 2 paragraphs breaks existing convention but I don't know a better way of separating the text or displaying it in a way that conveys the same idea. I figured if this tripped up one newbie it's bound to be a problem for a few others.
=> Add callout to potentially previous mix alias

src/pages/docs/screens.mdx
The "mobile-first" link in Screens docs doesn't properly link to the "Working mobile-first" section of the Responsive Design docs, this fixes it.
=> Fix broken anchor link

src/pages/docs/max-width.mdx
The example given for how to edit `tailwind.config.js` is not consistent with other pages, such as the page for [`width`](https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/width.mdx?plain=1#L151-L161).
("extend" is missing here)
=> Make `max-width` customization example consistent

src/pages/docs/guides/remix.js
This way it's in line with what we have in the `examples` repo (see https://github.com/remix-run/examples/pull/156): https://github.com/remix-run/examples/tree/main/tailwindcss
=> docs(guides/remix): update Remix guide

src/pages/docs/guides/remix.js
PR for docs updates. Remix first-class support for TailwindCSS just came out in v1.13.0 (https://github.com/remix-run/remix/releases/tag/remix%401.13.0) and we needed to update the docs. It looked like a PR was already merged to change most of it -- however, I found a slight bug that this PR fixes: https://github.com/tailwindlabs/tailwindcss.com/issues/1515.
=> remix-guide-updates

src/pages/docs/guides/nuxtjs.js
Nuxt v2.16 now includes PostCSS 8 by default and included some breaking-ish changes if you were using the separate PostCSS 8 plugin previously. This updates the guide to account for that and be more consistent with our other guides.
Fixes #1518
=> Update and simplify the Nuxt 2 guide for the now-included PostCSS 8

src/pages/docs/animation.mdx
Hello, small fix so people can copy and paste the html and have the exact same result as the one in displayed in the documentation.
Without the `relative` in the parent, the ping animation is fixated to the body of the website, and not the parent `span`.
Thanks, have a great day
=> Fix ping animation html code example

src/pages/docs/transition-delay.mdx, src/pages/docs/transition-duration.mdx
With the addition of `delay-0` and `duration-0` it is no longer necessary to show the `'0' : ' 0ms'` customisation examples on the `/transition-delay` and '/transition-duration` pages
=> Removes 0ms customisation examples from transitionDelay and transitionDuration

package-lock.json, package.json, src/pages/docs/font-size.mdx
Added `text-base/loose` to the `line-height` modifier example. 
It wasn't clear to me initially that these relative `line-height` classes would also work so thought it would help to clarify that. Feel free to discard if you disagree.
=> Updates `line-height` example on `/font-size` to include relative `line-height` class.

src/pages/docs/font-family.mdx
Adds documentation for customising `font-variation-settings` on the `/font-family` page. 
I combined it with `font-feature-settings` and renamed the section to "Providing default font settings"
=> Documents `font-variation-settings`

src/pages/docs/word-break.mdx
I noticed that `break-keep` wasn't documented on the `/word-break` page so I added it. Feel free to discard if this was intentional.
=> Documents `break-keep` utility

package-lock.json, package.json, src/pages/docs/justify-content.mdx
A couple notes:
- Because they are less commonly used I've put `justify-stretch` and `justify-normal` below the other utilities. Putting them at the beginning would mean that `justify-start`, `justify-stretch` and `justify-normal` would all display very similar behaviour.
- For `justify-stretch` I've provided different examples for the behaviour with `grid` and `flex` containers.
- I noticed that the `justify-stretch` and `justify-normal` classes aren't showing up in the quick start section:
=> Documents `justify-stretch` and `justify-normal` under `/justify-content`

src/pages/docs/align-content.mdx
Adds documentation for `align-content: stretch` and `align-content: normal`.
~~One weird thing: there is supposed to be a difference in behaviour between `align-content: stretch` and `align-content: normal`~~ 
_I'm an idiot._
=> Documents content-normal and content-stretch

package-lock.json, package.json, src/css/prism.css, src/navs/documentation.js, src/pages/docs/hyphens.mdx
Adds a new page `/hyphens` under the `typography` section.
I noticed that `hyphens` aren't showing up in search. Does this indexing only happen on the production site?
=> Documents `hyphens` utilities.

package-lock.json, package.json, src/navs/documentation.js, src/pages/docs/caption-side.mdx
This PR adds documentation for `caption-side` utilities and introduces a new page `/caption-side` under the `Table` heading.
Note: not sure what the insiders build should be. I've pinned it at `bcf983a` here.
=> Document caption-side utilities

src/pages/docs/guides/nuxtjs.js
The current URL in the tailwind docs redirects to nuxt.com but finally gives a 404.
Setting the correct final URL here. That's the one mentioned in `nuxt.config.ts` after a fresh `nuxi init`.
=> Update nuxtjs.js: Nuxt Config link

src/pages/docs/hyphens.mdx
In german we don’t use Pascal case for words, even this really long ones.
=> Fix german spelling in hyphens.mdx

src/pages/docs/gradient-color-stops.mdx
I have found a class names mismatch issue [in this page](https://tailwindcss.com/docs/gradient-color-stops#specifying-stop-positions)
```html
<div class="bg-gradient-to-r from-indigo-500 from-10% via-purple-500 via-30% to-pink-500 to-90% ..."></div>
```
The class names in the code snippet differ from those shown in the example. Specifically, while the example uses colors ranging from sky-500 to emerald-500, the code snippet instead uses colors ranging from purple-500 to pink-500, which is incorrect.
=> Fix: utility class names mismatch issue

src/pages/blog/tailwindcss-v3-3/index.mdx
In the logical properties section, the Physical counterpart (LTR) of `rounded-e-*` is `rounded-r-*` rather than `rounded-l-*`
=> Fix typo in v3-3 announcement

src/pages/docs/guides/nextjs.js
Hey Tailwind Team!
Tailwind, Next.js, and MDX are a popular combo. We've had a few reports where folks forgot to configure the content config option and were quite puzzled because 99% of styling is already covered, and the mdx subset of styles is so rare.
=> Add .mdx to tailwind config.content

src/pages/docs/place-items.mdx
Spotted a couple of duplicate classes when I was working through some of the examples in the docs site.
=> Removed duplicate gap class

src/pages/docs/guides/sveltekit.js
Removes an un-necessary step from the Sveltekit docs
Fixes #1588
=> Remove un-necessary step from sveltekit guide

next.config.js
This fixes building on Node >= 17.
We really should swap out file-loader for webpack's Asset Resources instead but that requires a bit more work. This is a good stop-gap measure until that gets done.
=> Fix building on newer versions of Node

src/pages/docs/presets.mdx
Under the "Disabling the default configuration section", the last example should have the same filename in the tailwind.config.js file as the filename of the preset file shown right above it, which is _my-preset.js_
=> Fix minor typo in the Presets documentation.

src/pages/docs/justify-self.mdx
Title says it all. Fixed a few typos in docs/justify-self.
=> docs/justify-self: Fixed typos

src/pages/docs/customizing-spacing.mdx
The pages for [`scrollPadding`](https://tailwindcss.com/docs/scroll-padding#customizing-your-theme) and [`scrollMargin`](https://tailwindcss.com/docs/scroll-margin#customizing-your-theme) mention using the spacing scale. Unfortunately these plugins are currently not listed on the [Customize Spacing](https://tailwindcss.com/docs/customizing-spacing) page.
I have not checked if any other plugins are missing in the list.
=> Added `scrollMargin` and `scrollPadding` to core plugins list for spacing customization

src/pages/docs/stroke-width.mdx
I plucked the wording from `border-width` for no particular reason.
=> docs(stroke-width): remove reference to grids

src/pages/docs/configuration.mdx
Closes #1604
In Tailwind CSS v3.3 we added support for configuring Tailwind in ESM and TypeScript. This PR updates the "Configuration" page in the docs to include a new "Using ESM or TypeScript" section that explains how to do this.
=> Add "Using ESM or TypeScript" section to configuration page

src/components/Heading.js, src/layouts/SidebarLayout.js
Resolves #1644
This PR improves the heading anchor links.
First, I tweaked the position of the sidebar navigation scrollbar so it's more to the left giving a little more space for the anchor link icon, and also moved the icon slightly to the right, so that the icon doesn't land on top of the scrollbar:
| Before | After |
|--------|--------|
| <img width="474" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/882133/1d978b40-bfae-40f6-a7ef-2e5bc198f891"> | <img width="515" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/882133/603996a1-a150-46c5-984f-92d1aa3d776a"> | 
Next, I removed the anchor link icon entirely on mobile (since there is no space for it), but then made the whole heading a link so that you can still click it.
| Before | After | …
=> Improve heading anchor links

src/components/Guides/TabBar.jsx, src/layouts/InstallationLayout.js
This PR is a continuation of #1653. I don't have push permissions on the original PR so had to create a new PR with the additional changes.
In short, on windows a scrollbar is shown on the installation pages in the tabbar because of the overflowing tab indicators that are floating on top of the gray border.
Closes: #1653
=> Fix unexpected installations tabs scroll (continuation of #1653)

src/pages/docs/guides/vite.js
Adds a Svelte section to the Vite framework guide, alongside React and Vue.
Direct preview link: https://tailwindcss-com-git-fork-lukemartin-guide-v-24e21b-tailwindlabs.vercel.app/docs/guides/vite#svelte
=> Add Svelte section to Vite framework guide

src/pages/docs/editor-setup.mdx
"editor-setup.mdx" was stating "Check out the plugin on GitHub learn more and get started." where the word "to" was missing before "learn more", so I forked and edited.
Hopefully PRing to the `master` branch is fine. I looked at the [CONTRIBUTING.md](https://github.com/tailwindlabs/tailwindcss/blob/master/.github/CONTRIBUTING.md) file and a preferred branch name wasn't specified it seems.
If I should have PRed in the `3.3` branch or another, please let me know and I'll do it. :)
Hope it helps!
Thank you so much for creating Tailwind ♥
=> Fixed missing "to" in editor-setup.mdx

src/pages/docs/theme.mdx
We talk about how to extend the theme but never discuss how you use the values within it. This PR adds a short snippet to the bottom of the docs discussing this.
Fixes #1571
Supersedes #1663
=> Add explanation of `theme.extend` to theme documentation

src/pages/docs/guides/sveltekit.js
[SvelteKit's documentation](https://kit.svelte.dev/docs/creating-a-project) uses `npm create svelte@latest my-app` instead of `npm init svelte@latest my-app`
`npm create` is an [alias](https://docs.npmjs.com/cli/v9/commands/npm-init?v=true) of `npm init`, so this change might not be necessary, but it might be beneficial to be coherent with SvelteKit's documentation.
Regards.
=> docs: use 'create' command alias for creation of sveltekit project

src/pages/docs/overscroll-behavior.mdx, src/pages/docs/scroll-behavior.mdx
I think this help text is misleading for this component. at least the hover state makes no sense in my opinion and lead to confusions. maybe remove that for this component?
the html container will have always a hover state if someone clicks anywhere in the content of the page. so the first style will never apply? maybe I am incorrect. No hard feeling if the MR get's closed :)
At least I was quite confused and I think this is only added, because lots of the help-pages have the states. 
Thx!
=> Change variant used on `scroll-behavior` docs

src/pages/docs/guides/nuxtjs.js
The file path `error.vue` does't exist in the tailwind configuration file for [nuxtjs](https://nuxt.com)
So I add it
`error.vue` file:
https://nuxt.com/docs/getting-started/error-handling#rendering-an-error-page
Example:
https://nuxt.com/docs/getting-started/error-handling#example
=> docs: Add error page path for nuxtjs guide

src/components/home/BuildAnything.js
From "Classic Utility Jacket" to "Utility Jacket" to match the figure displayed above it.
=> Fix typo in BuildAnything.js

src/pages/docs/content-configuration.mdx
The example extraction regex is missing the `g` flag, so it currently only finds the fix match. Add `g` so it find all matches in `content`.
=> Add missing `g` flag in custom extraction example

src/pages/blog/automatic-class-sorting-with-prettier/index.mdx
As of v3, Prettier [no longer autoloads plugins](https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker).
=> Document how to load the Prettier plugin

src/pages/docs/configuration.mdx
The text states that bold comes later than medium in the css, but the order in the code was the reverse. Tailwind gives preference to the later declaration, so font-bold should be after !font-medium. Now the example matches the text.
=> Corrected class order in documentation of !important utility

src/pages/docs/grid-template-rows.mdx
Adds documentation for the extended `row` scales (6-12)
https://tailwindcss-com-git-document-row-changes-tailwindlabs.vercel.app/docs/grid-template-rows
=> Document row scales

src/pages/blog/2022-08-17-tailwind-framer-motion-template-and-tailwind-jobs/index.mdx
Fix broken link to image reference.
I do understand this blogpost is outdated, but still, it's nice to reference to the working images API of NextJS
=> chore: fix broken link to NextJS Image API reference

src/pages/docs/guides/sveltekit.js
In SvelteKit 2, `vitePreprocess` is no longer exported from `@sveltejs/kit/vite`
It should be imported from `@sveltejs/vite-plugin-svelte`
Source: https://kit.svelte.dev/docs/migrating-to-sveltekit-2#vitepreprocess-is-no-longer-exported-from-sveltejs-kit-vite
=> Update sveltekit install guide.

src/pages/docs/grid-template-columns.mdx, src/pages/docs/grid-template-rows.mdx
Adds documentation for `grid-cols-subgrid` and `grid-rows-subgrid`
https://tailwindcss-com-git-document-subgrid-tailwindlabs.vercel.app/docs/grid-template-columns
https://tailwindcss-com-git-document-subgrid-tailwindlabs.vercel.app/docs/grid-template-rows
=> Document subgrid

src/navs/documentation.js, src/pages/docs/text-wrap.mdx
Adds documentation for `text-wrap`,`text-nowrap`, `text-balance` and `text-pretty`
https://tailwindcss-com-git-document-text-balance-a-b58a55-tailwindlabs.vercel.app/docs/text-wrap
=> Documents text-wrap utilities

src/navs/documentation.js, src/pages/docs/size.mdx
Adds documentation for the new `size-` utilities.
https://tailwindcss-com-git-document-size-utilities-tailwindlabs.vercel.app/docs/size
=> Documents size utilities

src/pages/docs/max-height.mdx, src/pages/docs/max-width.mdx, src/pages/docs/min-height.mdx, src/pages/docs/min-width.mdx
Adds documentation for the new fixed scales added to `min-h`, `max-h`, `min-w` and `max-w`
https://tailwindcss-com-git-document-min-max-scales-tailwindlabs.vercel.app/docs/min-width
https://tailwindcss-com-git-document-min-max-scales-tailwindlabs.vercel.app/docs/max-width
https://tailwindcss-com-git-document-min-max-scales-tailwindlabs.vercel.app/docs/min-height
https://tailwindcss-com-git-document-min-max-scales-tailwindlabs.vercel.app/docs/max-height
=> Documents min/max height/width scales

src/pages/docs/appearance.mdx
Adds documentation for `appearance-auto`
https://tailwindcss-com-git-document-appearance-auto-tailwindlabs.vercel.app/docs/appearance
=> Documents appearance-auto

src/navs/documentation.js, src/pages/docs/forced-color-adjust.mdx, src/pages/docs/hover-focus-and-other-states.mdx
Adds documentation for  the `forced-colors` modifier as well as `forced-color-adjust-none` and `forced-color-adjust-auto`
https://tailwindcss-com-git-document-forced-colors-tailwindlabs.vercel.app/docs/hover-focus-and-other-states#forced-colors-mode
=> Document Forced Colors 

src/pages/blog/tailwindcss-v3-4/index.mdx
I opened that section in a new tab and noticed the page wasn't scrolled to it, turns out it's just a tiny typo in the link.
=> Fix heading ID in the v3.4 news summary

src/pages/docs/customizing-spacing.mdx
In 3.4.0, the `min-width`, `max-width`, and `min-height` scales were extended to include the full spacing scale: https://tailwindcss.com/blog/tailwindcss-v3-4#extended-min-width-max-width-and-min-height-scales
=> Update customizing-spacing.mdx to reflect 3.4.0 changes

src/pages/docs/grid-template-rows.mdx
`grid-row-subgrid` -> `grid-rows-subgrid`
before|after
-|-
=> Fix typo in grid-template-rows subgrid

src/pages/docs/gap.mdx
“gap-x” should correspond to “between column”，the same as "gap-y"
=> fix : word order

src/pages/docs/guides/laravel.js
Working with version 3.4.1 of Tailwind CSS, there is no `module.exports` in the `tailwind.config.js` file, but `export default` instead.
=> update module export in Laravel guide

src/pages/docs/installation/index.js
The changes done in PR #1754 has an issue where the output.css file is not detected by the HTML file.
This is because the href points to `/output.css`.
A better approach would be to add a relative path since all the three files (index.html, input.css and output.css) are within a single folder `src`.
I have added a (.) so that the relative path is taken into consideration.
Please review.
=> Fix invalid path of the output.css file

src/pages/docs/box-decoration-break.mdx
There is no `clip-page` property, this was probably a typo.
List of affected properties can be found at https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break
=> Replace typo "clip-page" with "clip-path"

src/pages/docs/dark-mode.mdx
Renamed `Window.matchMedia()` to `window.matchMedia()` to give clarity that method of global variable `window` is being referred instead of `Window` interface instance method, and also analogous with the given example following the passage.
=> Fix: typo on window variable

src/components/Heading.js
Currently, on a blog post when using dark mode, the [hyperlink button](https://tailwindcss.com/blog/tailwindcss-v3-4#dynamic-viewport-units) on hover text colour is the same as the background colour leading to the icon disappearing on hover.
This change just adds `dark:hover:text-slate-100` to the icon.
See below:
Current hover | neutral state | fixed hover
=> Fix blog heading hyperlink hover on dark mode

src/pages/docs/text-overflow.mdx
In the Text Overflow documentation, "truncate" and "text-ellipsis" utilities have the same descriptions. This revision clarifies their differences.
=> Clarify description of "truncate" and "text-ellipsis"

src/pages/docs/dark-mode.mdx
Resolves #1766
This PR updates the dark mode page to include the new `selector` and `variant` strategies that came out in Tailwind CSS v3.4.1. It still (briefly) mentions the `class` strategy, just in case anyone is still on an earlier version of Tailwind, but ideally if you're enabling a class/selector based dark mode strategy its best to just upgrade to the latest version of Tailwind.
=> Document new `selector` and `variant` dark mode strategies

src/pages/docs/guides/adonisjs.js
Hey there! 👋🏻 
We should not have two `@vite()` tags inside the template.
=> fix(adonisjs): we should have only one vite tag

src/pages/docs/guides/parcel.js
Hi yall, this is a small fix to the documentation to make it easier to get started with tailwind and parcel. When I added parcel to my application built with parcel, I was following the guide and unfortunately it didn't work out of the box. After a bit of searching I came across the following issue on parcels gihub (https://github.com/parcel-bundler/parcel/discussions/7453).
This change essentially only adds the `type="text/css"` to the tutorial docs for parcel so that the framework parcel actually picks up the index.css file correctly and applies tailwind styles.
=> add correct type to css file link in parcel example

src/pages/docs/guides/remix.js
Recently, Remix migrated to Vite. With the update, the instructions within the Remix/Tailwind install guide no longer worked. 
Anytime I tried building the project, I'd get the following error:
I updated the docs to match the solution filed in this issue on Remix's side: https://github.com/remix-run/remix/issues/8832#issuecomment-1977696930
Key differences:
- Needs a postcss.config.js file
- Vite requires `?url` to respect the `.css` extension: `import stylesheet from "~/tailwind.css?url`
=> 💬 Update Remix Guide. Different config with Vite

src/pages/docs/using-with-preprocessors.mdx
1. Updated the link to the `postcss-nesting` repo.
2. Removed the "work-in-progress" label, as I think the CSS nesting spec is considered complete now.
=> Update links and description for `postcss-nesting`

src/pages/showcase/index.js
Fix the issue of frequent mouse movements in and out causing video playback to fail automatically
After playing the video once, it is easier to reproduce it by frequently moving it in and out again.
The state value has been fluctuating between leaving and looping.
=> Fix showcase video playback which periodically fails to restart

src/pages/docs/guides/remix.js
In the [Remix installation guide](https://tailwindcss.com/docs/guides/remix), the file name in the documentation are inconsistent with the file name in the code block. This PR fixed it.
=> Fix typo in the Remix installation guide

src/pages/docs/flex.mdx
Resolves #1803
This PR cleans up the [flex documentation](https://tailwindcss.com/docs/flex) a little by making the `flex-none` example make more sense.
Previously we weren't highlighting both the `flex-none` boxes, plus we only showed the size on one:
<kbd><img width="814" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/882133/cae6f93c-5439-4f8f-af60-bb22111b4fad"></kbd>
Now both of these boxes are highlighted in the dark indigo, and both have a size set:
<kbd><img width="811" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/882133/7839d7dd-7f50-42f1-bc8a-58081f7cdc12"></kbd>
I also updated some of the other flex examples to always have `w-14` for the first item (which is always set to `flex-none`).
=> Clean up `flex` docs

src/css/docsearch.css
When the browser text size is not set to `16px` some docsearch icons break.
**Before:**
The search icon is tilled and repeated instead of scaled
**After:**
The search icon size is scaled, the stroke width is not scalled and kept the same.
> [!NOTE]
> You can change the font size setting in chrome in the apperance settings.
> https://support.google.com/chrome/answer/96810#fontsize
=> fix: fixed search icon scaling in docsearch.css

src/css/docsearch.css
When the browser text size is not set to `16px` some docsearch icons break.
**Before:**
The remove from search and add search to favorites icon is tilled and repeated
**After:**
The remove from search and add search to favorites icon is centererd and not tilled anymore.
> [!NOTE]
> You can change the font size setting in chrome in the apperance settings.
> https://support.google.com/chrome/answer/96810#fontsize
=> fix: favorite and remove from search history icon no-repeat in docsearch.css

package-lock.json, package.json, src/components/PostItem.js, src/layouts/BlogPostLayout.js, src/layouts/JobPostingLayout.js, src/pages/blog/index.js, src/utils/formatDate.js
👋🏼 **NOTE:** I am reopening this as a follow-up to #1811. I closed that one thinking that I might need to install another dependency to polyfill `Intl.DateTimeFormat` for server use, but that does not appear to be the case.
I'm unable to inspect the failures that caused the previous PR's build to fail, as I am not part of the `tailwindlabs` org on Vercel and do not have access to the `tailwindlabs/tailwindcss-com` resource.
If you report the failures here, I can take a stab at resolving them.
---
This PR will…
1. **resolve a date mismatch issue caused by `tinytime` not preserving timezone information**
I noticed this when sharing the job app links on Twitter. I'm not sure if this occurs in every time zone, or if I'm only seeing it because I'm currently traveling in Los Angeles.
2. …
=> Resolve date discrepancy and remove tinytime dependency

src/pages/docs/installation/play-cdn.js
Update docs (play-cdn page) to include container queries plugin in cdn link.
Docs can be updated because https://github.com/tailwindlabs/tailwindcss/issues/12667 was fixed, and now can show on docs page that CDN allows user to play with this plugin too.
=> Update docs (play-cdn page)

src/pages/blog/headless-ui-v2/index.mdx
In the new checkbox component example there is a missing import of the `Description` component. This PR adds it and sorts the imports alphabetically
=> docs: missing import in checkbox example

src/pages/docs/top-right-bottom-left.mdx
issue: HTML Element is missing end tag.
solution: Corrected typo where the "/" character was missing in the end-tag.
=> docs: Corrected HTML end-tag typo

src/pages/docs/overflow.mdx
'Flight to vancouver' corrected to 'Flight to Vancouver'
=> Fix capitalisation in a demo in overflow.mdx

src/components/ThemeReference.js
- added a line to the description Array to ensure the `textColor` theme property is translated to `color` in the docs table, since `text-color` is not a valid CSS property
=> Update ThemeReference.js to accurate text color css property

src/pages/docs/gradient-color-stops.mdx
This PR adds a short sentence outlining the fact that `to-*` color stops need to be redefined when a variant modifier is used on the `from-*` color.
Explaining why this happens — the intelligent transparency fade calculation (RGB with 0 alpha) — is probably "too much info", but I thought it was useful to just mention the behaviour.
=> Add clarification about preserving the same `to-*` color stop

src/pages/docs/utility-first.mdx
1.   Updated the logo size class to **size-12** instead of **h-12 w-12.**
2.   Modified the documentation to include the use of the new size utility, providing clear examples for new Tailwind CSS users.
=> Update logo size utility to use `size-12` instead of `h-12 w-12`

src/pages/docs/play-cdn.mdx
I stumbled upon this broken page on the website: https://tailwindcss.com/docs/play-cdn
It doesn't appear to be linked to from anywhere (all links instead go to https://tailwindcss.com/docs/installation/play-cdn), so this seems safe to delete.
=> Remove empty Play CDN page

src/pages/docs/customizing-colors.mdx
This PR updates the color documentation to remove mention of the `<alpha-value>` placeholder because it can lead to unexpected issues like [this one](https://github.com/tailwindlabs/tailwindcss-typography/issues/360) and isn't actually necessary.
It was only necessary for supporting the old deprecated `text-opacity-*`, `bg-opacity-*`, etc. utilities, but those have been undocumented for almost three years, so I feel comfortable not mentioning this anymore.
=> Remove <alpha-value> from docs

package-lock.json, package.json, src/css/docsearch.css
This PR updates DocSearch to its latest version.
There was a regression on the DocSearch indexing side, which broke the `lvl0` header (used to create search results section). We released a library side fix in order to prevent impacting the quality of the searches in the meantime of the indexing fix, and also prevent future regressions.
The current https://tailwindcss.com/ results:
With the fix applied:
=> chore: update DocSearch version

src/components/home/BuildAnything.js
Tailwind css website homepage build anything section's simple tab contain output image and code editor but in code, developer's forget to write complete words "Classic Utility Jacket". So i'm just write correct words as you can check/compare before and after changes🙂.
Sorry, if i am wrong otherewise please add my changes into your website.
Thank You,
beginner developer
=> Fix typo on homepage build anything section's simple tab show code editor and output Classic Utility Jacket

src/pages/docs/reusing-styles.mdx
Fixed a grammar issue in the ‘Multi-cursor editing’ section by adding the verb ‘is’ to make the sentence sound more grammatically correct.
=> Fix grammar in reusing-styles.mdx

src/pages/docs/v4-beta.mdx
Fix a typo in the v4 migration docs where the v3's `last:*:pb-0` should be `*:last:pb-0` but is (incorrectly) written as `*:first:pb-0`
=> Fix typo in v4 stacked variants migration example

src/pages/docs/v4-beta.mdx
I was reading the document on v4-beta and at the table I wasn't able to see that `--spacing-*` namespace. At first I thought maybe it has been removed due to the fact that `mt-21` is now available ( mentioned earlier in document ). But soon I realized maybe it was just missed out in table. So, that's it.
=> Add `--spacing-*` to namespace-reference table ( v4 docs )

src/pages/docs/v4-beta.mdx
In the 4.0 beta documentation there in the section:
Since Tailwind CSS v4.0 includes CSS variables for all of your theme values, we recommend using those variables instead of the theme() function whenever possible:
We have:
```css
@import "tailwindcss";
.my-class {
background-color: theme(colors.red.500);
background-color: var(--colors-red-500);
}
```
But i suppose that `var(--colors-red-500);` should be `var(--color-red-500);`
(color without the 's')
=> fix color from colors in the theme() replacement with var()

src/components/home/EditorTools.js
Before:
After:
No idea why this class was there tbh
=> remove z-index on beam

src/pages/docs/v4-beta.mdx
```diff
- Next, add our PostCSS plugin to your `postcss.config.js` file:
+ Next, add our PostCSS plugin to your `postcss.config.mjs` file:
```
Because the file below is a `.mjs` file with modules
=> docs: Fixing typo of postcss.config.mjs

src/pages/docs/guides/angular.js
On the page for installing Tailwind in an Angular project, the link to the Angular CLI redirects to an old version of the Angular docs.
``<a href="https://angular.io/cli">Angular CLI</a>``
Update the link to new Angular docs.
`<a href="https://angular.dev/tools/cli">Angular CLI</a>`
=> docs: fix link to new angular docs

src/pages/docs/v4-beta.mdx
As mentioned in https://github.com/tailwindlabs/tailwindcss/issues/15120#issuecomment-2497547702, the upgrade tool requires Node v20+ but it's not listed on the docs page.
=> [v4] Add Node v20 requirement for the upgrade tool

src/pages/docs/guides/astro.js
The docs [currently state](https://tailwindcss.com/docs/guides/astro) that running `npx astro add tailwind` will add `@astro/tailwind`. This is incorrect, it is actually `@astrojs/tailwind`. See attached screenshot of terminal output.
=> Fix: Fixing `@astro/` typo -> `@astrojs`

src/blog/tailwindcss-v4/index.mdx
An example had 17 where it should have 8
=> Fix random typo in index.mdx

src/docs/preflight.mdx
Especially fixes the code example for disabling Preflight.
=> Changes `@import` paths to be consumer-facing

src/docs/theme.mdx
Updated the CSS variable from `var(--bg-mint-500)` to `var(--color-mint-500)` in the div element.
=> Fix typo in theme page example

src/components/home/why-tailwind-css-section.tsx
The name of: أحم is an incomplete misspelling of the name: أحمد in the arabic language.
=> fix: correct typo in arabic name

src/docs/margin.mdx
Page: [margin - Spacing](https://tailwindcss.com/docs/margin#using-logical-properties)
Fixes the margin logical properties example where it doesn't reflect the difference when `dir="rtl"` is set. The example also utilises the `ms-8` & `me-8` classes.
=> fix: updated the margin logical properties example code

src/docs/adding-custom-styles.mdx, src/docs/dark-mode.mdx, src/docs/functions-and-directives.mdx, src/docs/hover-focus-and-other-states.mdx
(Sorry if I misinterpreted the intentions of `@custom-variant` and `@variant`)
- Replaces code usages of `@variant` to `@custom-variant` as per tailwindlabs/tailwindcss#15663.
- Disambiguates some usage of `@variant` in examples to show that it should be used inside a rule, and not at the root.
=> Prefer `@custom-variant` over `@variant`

src/components/header.tsx
Adds the same size for the search button on the header as the menu button next to it.
I searched for other occurrences of `SearchButton` but it's used with it's own padding in all other places, so I didn't change the `SearchButton` component directly.
=> Increase size for search button to improve accessibility on mobile

src/docs/hover-focus-and-other-states.mdx
This pr adds the missing class name `dark:hover:file:bg-violet-700` in the [::file](https://tailwindcss.com/docs/hover-focus-and-other-states#file) example provided in the documentation.
=> fix(docs): add missing bg class for dark variant on hover

src/docs/background-image.mdx
Fix a missing hyphen for custom background image linear gradient.
=> Fix bg-linear custom variable typo

src/docs/compatibility.mdx
As per tailwindlabs/tailwindcss#15389.
Pointed out by tailwindlabs/tailwindcss#15771.
=> Update Chrome supported version

src/docs/flex.mdx
The arbitrary value is discussed further down the page but missing in the API table.
=> Add missing arbitrary value option to `flex` API table

src/docs/justify-content.mdx
Fix issue [#2009 ](https://github.com/tailwindlabs/tailwindcss.com/issues/2009)
=> Fix: typo error in justify-content

src/app/(docs)/docs/installation/framework-guides/sveltekit.tsx
In Svelte 5, content can be passed to components in the form of snippets and rendered using render tags.
In legacy mode, content inside component tags is considered slotted content, which can be rendered by the component using a <slot> element
https://svelte.dev/docs/svelte/legacy-slots
=> Update sveltekit.tsx - to svelte 5 syntax

src/docs/detecting-classes-in-source-files.mdx
It looks like this page description was copypasted from [the dark-mode page](https://github.com/tailwindlabs/tailwindcss.com/blob/af7b452ad5ccf09f47961d09420663ebdd606140/src/docs/dark-mode.mdx?plain=1#L7).
=> Fix page description for "Detecting classes in source files"

src/docs/flex.mdx
Replaced flex-[<custom-property>] with flex-(<custom-property>) to align with the intended syntax and ensure consistency across the codebase.
=> fix: correct syntax for flex custom properties

src/blog/automatic-class-sorting-with-prettier/index.mdx
**Blog page:** 
[Automatic Class Sorting with Prettier](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier)
**Problem:**
The "before" and "after" code snippets in the blog post are identical. It seems the Prettier plugin unintentionally formatted the "before" snippet as well. 😉
Issue: https://github.com/tailwindlabs/tailwindcss.com/issues/2020
**Fixes:**
- Updated the "before" code snippets to reflect the intended unformatted state.
=> Blog: Automatic Class Sorting with Prettier - Fix examples

src/pages/docs/guides/adonisjs.js, src/pages/docs/guides/angular.js, src/pages/docs/guides/create-react-app.js, src/pages/docs/guides/emberjs.js, src/pages/docs/guides/gatsby.js, src/pages/docs/guides/laravel.js, src/pages/docs/guides/meteor.js, src/pages/docs/guides/nextjs.js, src/pages/docs/guides/nuxtjs.js, src/pages/docs/guides/parcel.js, src/pages/docs/guides/qwik.js, src/pages/docs/guides/remix.js, src/pages/docs/guides/rspack.js, src/pages/docs/guides/solidjs.js, src/pages/docs/guides/sveltekit.js, src/pages/docs/guides/symfony.js, src/pages/docs/guides/vite.js, src/pages/docs/installation/index.js, src/pages/docs/installation/using-postcss.js
This PR uses `tailwindcss@3` in the installation instructions. 
Fixes: #2018
=> use `tailwindcss@3` in v3 docs

src/docs/upgrade-guide.mdx
Closes https://github.com/tailwindlabs/tailwindcss/issues/15773
=> Document button cursor change

src/docs/upgrade-guide.mdx
At the [Using the theme() function](https://tailwindcss.com/docs/upgrade-guide#using-the-theme-function) section docs advice to use `var()` over `theme()`, but there is a part of code where `theme()` is still used
=> Replace usage of `theme()` to `var()` as recommended by Tailwind v4

src/docs/padding.mdx
The `padding` docs say that e.g. `p-px` translates to `padding: calc(var(--spacing) * 1px);` which is not true.
As with the `margin` utilities, `p-px` translates to `padding: 1px;`.
=> Fix `padding` documentation

src/docs/styling-with-utility-classes.mdx, src/docs/theme.mdx
This PR adds documentation for the `important` option on the `@import "tailwindcss";` at-rule.
Remaining questions:
Fixes: https://github.com/tailwindlabs/tailwindcss.com/issues/2028
=> Document the `important` option

src/docs/adding-custom-styles.mdx
Correct CSS variable names in modifiers example
- Changed `--font-size-*` to `--text-*`
- Changed `--line-height-*` to `--leading-*`
https://tailwindcss.com/docs/adding-custom-styles#modifiers
=> Fix `adding-custom-styles` documentation

src/docs/styling-with-utility-classes.mdx
Closes #2014
This adds a section about how to use the `prefix(…)` option to the `/styling-with-utility-classes` docs.
=> Add section about `prefix(…)`

src/docs/font-family.mdx
This PR adds an example for the `font-family` utilities using Google Fonts.
The main reason for this example is just to showcase that you have to put the `@import url(…)` at the top of the file (above the `@import "tailwindcss";`). Not sure if documentation by example in this scenario is _enough_.
We could also document this behavior in another spot, but I think an example like this is more helpful.
If we want to document it somewhere else, we could put it on this page: https://tailwindcss.com/docs/styling-with-utility-classes
=> Document font-family example using Google Fonts

src/app/(docs)/docs/installation/framework-guides/astro.tsx
The first step of the [Astro framework guide](https://tailwindcss.com/docs/installation/framework-guides/astro) links to the Astro documentation for `create astro` using a link to the docs landing page and an anchor that doesn't exist on this page.
After discussing with the Astro docs team, this PR updates the link to point to https://docs.astro.build/en/install-and-setup/#install-from-the-cli-wizard which is a more appropriate link for the `create astro` command.
=> Fix `create astro` link

src/components/api-table.tsx
This PR fixes an issue where the `show more` link was sitting on top of the
mobile navbar.
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/7d92d518-a277-42ab-82ad-9dbb1a409500) | ![image](https://github.com/user-attachments/assets/b593cbc9-5025-43cc-8ff0-8fccc4660d75) |
=> Fix `show more` link sitting on top of the mobile navbar

src/app/typography.css
This PR fixes an issue where if you click on a link that goes to a specific header in the current page, then the header you scroll to is not visible on mobile
We already used `scroll-margin-top` on desktop, but we didn't take the second navbar (with breadcrumbs) into account.
If you visit this link: https://tailwindcss.com/docs/scroll-padding#using-logical-properties, then you will see the following:
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/20667556-4729-42f1-9bce-8125ea9df9b1) | ![image](https://github.com/user-attachments/assets/08bec67e-06d2-41c0-a06d-a7475fcc147d) |
=> Ensure headers are visible on mobile

src/docs/accent-color.mdx
In the opacity setting of the accent color, the black color that is not in the code in the example is being used.
I modified it to purple just like the example code.
- AS-IS
- TO-BE
=> fix: text in accent-color input's label

src/docs/upgrade-guide.mdx
Closes https://github.com/tailwindlabs/tailwindcss/issues/16372
Closes https://github.com/tailwindlabs/tailwindcss/issues/16395
- Adds a section about the changes to how prefixes work
- Adds a section about `space-x-*` and `space-y-*` utility changes
- Adds a section about dialogs now having margins in preflight
=> Upgrade guide changes

src/docs/upgrade-guide.mdx
`latest` is getting new versions, while `next` isn't.
https://www.npmjs.com/package/@tailwindcss/upgrade?activeTab=versions
=> Fix version tag for upgrade tool

src/app/(docs)/docs/installation/framework-guides/sveltekit.tsx
This is necessary to silence linter warnings from VSCode’s CSS language server.
Closes https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1147
Without this you'll see this in a Svelte document that uses `<style>` tags and `@reference`:
After you'll see the diagnostic is gone:
=> Add `lang="postcss"` to SvelteKit guide example

src/docs/background-repeat.mdx
Fixes #2091 
- Fixed incorrect URL syntax in `bg-[url()]` by ensuring proper closing of quotes.
- Updated `bg-[url(/img/clouds.svg')]` → `bg-[url(/img/clouds.svg)]`
=> Fix #2091: Correct URL syntax in background-repeat docs

src/docs/preflight.mdx
Changed the Preflight stylesheet link to the correct branch on GitHub.
Not sure if you want to keep the link pointed to GitHub, or use [a link to unpkg](https://unpkg.com/tailwindcss@^4/preflight.css) like the [v3 docs](https://v3.tailwindcss.com/docs/preflight) did.
=> Fix preflight stylesheet link

src/docs/functions-and-directives.mdx, src/docs/upgrade-guide.mdx
Closes #2015
- Mention that `corePlugins`, `safelist`, and `seperator` no longer exist in v4
- Mention `@layer components` in the `@layer utilities` section
=> Improve upgrade guide

src/docs/background-position.mdx, src/docs/font-family.mdx
Some *Using a custom value* sections are missing type hints for CSS variable usage examples. This PR adds them in.
=> Add missing type hints in usage examples

src/docs/responsive-design.mdx
This has been causing repeated confusion already so let's add a section to clarify this.
Closes #2099
=> Add a paragraph on breakpoint sorting

src/docs/colors.mdx
Fixed a missing `color:` on a `&:hover` example in: https://tailwindcss.com/docs/colors#referencing-in-css
=> Fix missing color: on doc example

src/docs/theme.mdx
This PR adds documentation for the new `@theme static` option to always include
all CSS variables from a theme block.
Merge once https://github.com/tailwindlabs/tailwindcss/pull/16211 is released.
=> Document `@theme static` 

src/app/(docs)/docs/installation/framework-guides/phoenix.tsx
Hey! I updated the Phoenix Framework installation instructions:
- Bump the `tailwind` plugin version to 0.3, as previous versions do not support Tailwind v4
- Changed paths so you no longer need to tell Tailwind CSS where to look for utilities
The installation instructions are now consistent with the instructions from the plugin README: https://github.com/phoenixframework/tailwind
=> Update Phoenix framework guide

src/docs/field-sizing.mdx
Fixes a minor typo on the `field-sizing.mdx` and fixes the company name so it's congruent with `hover-focus-and-other-states.mdx`
=> Fix: docs field sizing typo

src/docs/border-style.mdx
This PR adds a colon where one would be expected after a code description, and also adds a preposition "to" achieve proper grammar.
=> Missing colon and preposition

src/app/(docs)/docs/installation/(tabs)/play-cdn/page.tsx
UNPKG has not been actively maintained and ~~has been down since `Mar 15, 2025`~~ was down from Mar 15, 2025, 2:00 AM and down for 18 hours (https://github.com/unpkg/unpkg/issues/412). Migrating to jsDelivr means a more stable and reliant service.
The PR replaces UNPKG usage with jsDelivr.
The PR fixes https://github.com/tailwindlabs/tailwindcss/issues/17215 and https://github.com/tailwindlabs/tailwindcss/discussions/17216
=> Fix: replace UNPKG w/ jsDelivr

src/docs/box-shadow.mdx
This PR addresses a typo in the CSS variable declaration for shadow colors and inset shadows. 
Specifically, it adds the missing colon `:` to the `--tw-shadow-color` and `--tw-inset-shadow-color` declarations, ensuring they follow the correct CSS syntax.
=> Fix: add missing colon in box shadow CSS vars

src/app/(docs)/docs/installation/(tabs)/framework-guides/page.tsx
I noticed that the Tailwind CLI link at the bottom of the framework guides page does not work.
This PR fixes that by changing the link from `/docs/installation` to `/docs/installation/tailwind-cli`.
=> Fix link to Tailwind CLI tab on Framework Guides page

src/components/home/why-tailwind-css-section.tsx
The current behavior of the RTL part in the `WhyTailwindCssSection` is wrong, and I'll describe the problem in the following points.
- The RTL part does not have `dir="rtl"`
The DOM elements are ordered manually instead of leaving the order the same, and depending on the browser to order them according to their direction. So, in the RTL version, the image is the second element, but in the LTR, it's the first.
The `text-right` is used explicitly on the RTL version, although it should have been prefixed with `rtl:` or omitted entirely if the `dir` is set up correctly.
- The missing `dir` causes another issue with the truncation, as the direction of the container is `ltr`, so the truncation happened from the start of the text, not the end. 
How it looks: …
=> fix: properly setup rtl truncation to truncate from the end

src/app/(docs)/docs/index.tsx, src/docs/overflow-wrap.mdx, src/docs/word-break.mdx
Also removes `break-words` from the `word-break` docs, although it will still work for backwards compatibility.
=> Documents `overflow-wrap` utilties

src/docs/adding-custom-styles.mdx, src/docs/functions-and-directives.mdx, src/docs/hover-focus-and-other-states.mdx
This PR improves the `@custom-variant` docs, including:
1. Updating the "Adding custom variants" section on the "Adding custom styles" page to actually explain the `@custom-variant` directive, instead of the `@variant` directive.
2. Creating a new "Using variants" section on the "Adding custom styles" page to explain the `@variant` directive.
3. Updating the "@custom-variant" section of the "Functions and directives" page to remove the "pointer-coarse" example (in preparation for v4.1), and also link to the new "Adding custom variants" section on the "Adding custom styles" page, instead of the "Registering a custom variant" on the "Hover, focus, and other states" page. The "Adding custom styles" page is now considered the canonical location for this information.
4. Simplifying the …
=> Improve the `@custom-variant` docs

src/docs/hover-focus-and-other-states.mdx
This PR adds the new `details-content` variant to the "Hover, focus, and other states" page.
=> Document `details-content` 

src/app/(docs)/docs/installation/framework-guides/laravel.tsx
The current link points to the Laravel 11.x docs, which are now outdated, Laravel is currently at 12.x.
This PR updates the URL to use the version-agnostic link so it always points to the latest docs.
=> Update Laravel doc link to always point to latest version

src/docs/text-shadow.mdx
`shadow-<color>` is used for box-shadow, the right name is `text-shadow-<color>` according to https://github.com/tailwindlabs/tailwindcss/pull/17389.
=> Fix incorrect text-shadow color name in API table

src/docs/adding-custom-styles.mdx
This PR adds documentation for the new `--value('…')` and `--modifier('…')` where you can use literal values in strings.
To support literal values, use the `--value('literal')` syntax (notice the quotes):
```css
@utility tab-* {
tab-size: --value('inherit', 'initial', 'unset');
}
```
This will match utilities like `tab-inherit`, `tab-initial`, and `tab-unset`.
=> Document literal values in `--value('…')`

src/docs/height.mdx, src/docs/max-height.mdx, src/docs/min-height.mdx
These line-height-based sizing utilities were added in [tailwindcss#17790](https://github.com/tailwindlabs/tailwindcss/pull/17790) and released in **v4.1.5**.
This PR adds the following utilities to their respective documentation pages:
- `h-lh` → `height` page
- `min-h-lh` → `min-height` page
- `max-h-lh` → `max-height` page
=> docs: add `h-lh`, `min-h-lh`, `max-h-lh` utilities to height, min-height, and max-height docs

src/docs/styling-with-utility-classes.mdx
Fix unbalanced parentheses in an example, as spotted by tailwindlabs/tailwindcss#17857.
=> Fix example syntax error

src/blog/tailwindcss-v3-3/index.mdx
This PR fixes an issue where in the Tailwind CSS v3.3 blog post, we were using Tailwind CSS v4 variable shorthand syntax.
Fixes: #2232
=> Fix arbitrary shorthand syntax to use v3 syntax instead of v4 syntax

src/docs/font-variant-numeric.mdx
I think it was just a typo.
Before: 
After:
=> Fixed typo in font-variant-numeric.mdx to properly show the slashed-zero

src/components/code-example.tsx
This basically reverts the FF fix from #2126 which fixed FF but broke word highlights. Also divs aren't allowed in `<code>` elements so Shiki's assumption that it really only needs to look inside `<span>`s isn't a terrible one in this case.
We'll have to come up with some other solution to work around the FF bug
=> Fix word highlights

src/docs/upgrade-guide.mdx
Closes https://github.com/tailwindlabs/tailwindcss/issues/18058
=> Add note about preprocessors to the upgrade guide

src/mdx-components.tsx, tsconfig.json
This fixes a couple of things.
- The argument was removed from `useMDXComponents()`. In reality this function doesn’t receive any arguments.
- Components overrides are defined outside of `useMDXComponents()`. `useMDXComponents()` is called during render. Defining React components during render causes unnecessary re-renders and loss of state.
- The `**/*.mdx` glob is included in the `tsconfig.json` include patterns. This makes `.mdx` files part of the same TypeScript program in the editor. This leads to a better editor experience and reduced memory and CPU usage.
- This augments the `mdx/types` module to define the `JSX` namespace. React 18 defined the global `JSX` namespace. React 19 no longer does this. This leads to type errors in `mdx/types` resulting unresolved `any` types. This …
=> Enhance the MDX setup

src/app/(docs)/docs/installation/(tabs)/tailwind-cli/page.tsx
Closes #2275
Instead of linking to the old blog post we'll just link to the place you can download them. The instructions for using it are the same as the normal CLI you just invoke the CLI directory instead of node / bun / npx / etc…
=> Update “standalone executable” link

src/docs/hover-focus-and-other-states.mdx
The generated child selector has the same specificity as the regular one, so the reason it can't be overridden is just the CSS order.
=> Fix misleading text in "Hover, focus, and other states" page

src/docs/adding-custom-styles.mdx
`<length>` × `<percentage>` or `<length>` × `<length>` in `calc()` is invalid. This makes the example misleading. I've rewritten the example utility with valid examples.
=> Improve Negative Values example

src/blog/tailwindcss-v4-1/index.mdx
Fixed a link in a blog post that wasn't correctly pointing to the corresponding section.
=> Fix hash link in table of contents

src/app/(docs)/docs/installation/framework-guides/laravel.tsx
Description
---
This PR updates the documentation to reflect the actual default integration of Tailwind CSS in Laravel as shown in the official [Laravel repository](https://github.com/laravel/laravel/blob/12.x/resources/css/app.css).
Reason
--
The current Tailwind documentation for Laravel does not accurately reflect how Tailwind is integrated by default in the latest Laravel releases. This update ensures that new users following the guide get a setup experience that matches the actual Laravel boilerplate.
=> Update Tailwind CSS integration example for Laravel

src/docs/adding-custom-styles.mdx
• Fix CSS variable syntax from `var(--spacing-6)` to `--spacing(6)` in custom styles documentation
• Update to align with Tailwind CSS v4 variable syntax conventions
=> Fix CSS variable syntax in adding-custom-styles docs to use `--spacing`

src/mdx-components.tsx
This should hopefully stop all the RSC prefetches from happening on page load.
=> Don’t render Next `<Link>` for `/plus` urls

src/docs/transition-property.mdx
Updates `transition-property` values as per tailwindlabs/tailwindcss#15690 and tailwindlabs/tailwindcss#17812.
see tailwindlabs/tailwindcss#18793
=> Update transition property values

src/docs/background-image.mdx
According to the API map above, I thought this part should be `<value>` instead of `<image>`.
=> fix background-image api map error

src/docs/transition-property.mdx
See https://github.com/tailwindlabs/tailwindcss/pull/18795
This should be merged since 4.1.13 is out.
=> Drop `visibility` from `transition` utility

src/components/docs-sidebar-autoscroll.tsx
Previously, when navigating between documentation pages using the `command palette (⌘K)`, the sidebar would not automatically scroll to highlight the current page location. This made it difficult to maintain context of where you were in the documentation structure.
This PR enhances the `DocsSidebarAutoscroll` component to respond to navigation changes by:
- Adding pathname dependency to useLayoutEffect
- Making the sidebar auto-scroll to the active page whenever navigation occurs
- Maintaining the same smooth scrolling behavior as the initial page load
Now the sidebar will properly scroll to the current documentation page regardless of how you navigate to it - whether through direct clicks or command palette navigation.
=> fix: Docs sidebar auto-scroll not working on page navigation
