- source/docs/spacing.blade.md
Bring consistency with tailwindcss/tailwindcss#499
> Add more default spacing sizes

- source/docs/spacing.blade.md
- source/docs/svg.blade.md
Just like we use [in the partial](https://github.com/tailwindcss/docs/blob/master/source/_partials/variants-and-disabling.blade.php#L19) 🙂
> Change state variants title

- source/docs/svg.blade.md
> Add 'active' state variant

- navigation.php
- source/_partials/variants-and-disabling.blade.php
- source/docs/border-collapse.blade.md
- Added support for the `false` state variant
- Added support for the empty (`[]`) state variant
- Added `border-collapse` utilities
> Add border-collapse utilities

- source/_assets/js/nav.js
- source/_layouts/documentation.blade.php
Responsive menus are horrible.
> Prevent scrolling past mobile menu on long pages

- navigation.php
- source/docs/table-layout.blade.md
Bring consistency with tailwindcss/tailwindcss#504
> Add table-layout utilities

- source/docs/state-variants.blade.md
Just a small keyword correction.
> Text Correction

- source/_partials/color-palette.blade.php
- source/docs/colors.blade.md
- webpack.mix.js
Display color palette in a nicer more condensed way.
> Horizontal layout for color palette

- source/docs/overflow.blade.md
This PR adds the two classes added by [this other PR](https://github.com/tailwindcss/tailwindcss/pull/445) to the docs.
> Add independent axis overflow hidden to the docs

- source/index.blade.php
On the docs, the key says 'maxWidth' but within the default config file, it is 'width' as it should.
> Consistent naming

- navigation.php
- source/docs/object-fit.blade.md
- source/docs/object-position.blade.md
Docs for tailwindcss/tailwindcss#500
> [0.7] Add object-fit & object-position utilities

- source/_layouts/documentation.blade.php
- source/docs/what-is-tailwind.blade.md
- source/redirects
Current homepage is pointless :)
> Use "What is Tailwind?" page as the homepage

- source/docs/what-is-tailwind.blade.md
See: https://github.com/tailwindcss/docs/pull/40
> Remove dots when using `@apply`

- source/_assets/less/docsearch.less
- source/_assets/less/main.less
- source/docs/colors.blade.md
- source/docs/configuration.blade.md
- source/docs/controlling-file-size.blade.md
- source/docs/functions-and-directives.blade.md
- source/docs/plugins.blade.md
- source/docs/responsive-design.blade.md
`Replacing the config() function with the new theme() function`
https://github.com/tailwindcss/tailwindcss/pull/697
> rename config() to theme()

- source/docs/letter-spacing.blade.md
**Update letter-spacing values and usage.** 
Should responsive example be updated too, wasn't sure which should put as there is 6 scales and 5 screens?
> Update letter-spacing values and usage

- source/docs/spacing.blade.md
Not sure how to go with the __Customizing__ sections. 
Looks like there is still an open issue about it https://github.com/tailwindcss/tailwindcss/issues/736
> 1.0 - Updates spacing points

- source/_partials/color-palette.blade.php
- source/docs/colors.blade.md
This PR adds back the color palettes to the Colors page. Only thing I'm not sure about is the placement of the black and white colors.
> Add color palettes to Colors page

- source/docs/adding-new-utilities.blade.md
- source/docs/extracting-components.blade.md
- source/docs/functions-and-directives.blade.md
- source/docs/installation.blade.md
not sure if the links to CDN and GitHub are going to be correct 🤔
> Change preflight to base

- source/docs/colors.blade.md
Please double check that the way the colors are accessed in the code examples are correct 🙏
> Updating the copy and example on the colors page

- source/docs/line-height.blade.md
Same as #104, but for the line heights page. This also updates the code samples to read from the theme config.
> Update line heights page

- webpack.mix.js
Updated the `webpack.mix.js` file to resolve the theme configuration before writing it out to `tailwind.json`.
I've added this to continue the updates of reading class table content from configuration instead of hard-coding them. Let me know if you want to continue down this path or would rather keep the system as it is now!
> Use resolveConfig to get access to evaluated theme values

- source/docs/width.blade.md
Following up on the previous PR (#109), this updates the Width page to read the values from config. I've also updated the copy for the new fixed width utility count, and the config customization section to reflect the latest configuration updates.
> Update width page

- navigation.php
Update the navigation to link to the moved Box Shadows page
> Update link to Box Shadows page

- source/docs/object-position.blade.md
Document the new object-position customization possibilities. Wasn't sure if the 'features' section at the top was required, but added it for completeness.
> Document object-position customization options

- source/docs/configuration.blade.md
> Correct text-indigo-dark typo

- source/docs/cursor.blade.md
Document the new cursor customization possibilities.
> Document cursor customization options

- source/docs/border-width.blade.md
This PR adds documentation for the responsive helpers as well as customizing the generated border widths.
I did not remove the 'Work in progress' as I wasn't sure if you would want to add anything else to the page.
> Update Border Width documentation

- source/docs/float.blade.md
This PR adds documentation for all the float utilities and its responsive features.
> Document all float utilities

- source/docs/align-content.blade.md
- source/docs/align-items.blade.md
- source/docs/align-self.blade.md
- source/docs/flex-direction.blade.md
- source/docs/flex-wrap.blade.md
- source/docs/font-size.blade.md
- source/docs/justify-content.blade.md
- source/docs/letter-spacing.blade.md
- source/docs/text-color.blade.md
This PR fixes the incorrect variant name references in the variants/disabling section
> Fix incorrect variant name references

- source/docs/object-position.blade.md
Documented all the object position utilities and responsive features. Used the same image as the Object Fit documentation from Unsplash for the demos.
> Update object position documentation

- source/docs/flexbox-justify-content.blade.md
Subheading is missing a "how".
> Add missing "how"

- source/docs/letter-spacing.blade.md
Document customization of letter spacing values
> Add customization docs to letter spacing

- source/docs/vertical-align.blade.md
Add documentation for all utilities and responsive examples
> Finish vertical alignment docs

- navigation.php
Added missing letter. `Text Tranform` -> `Text Transform`
> Fix typo in navigation.php

- source/docs/background-attachment.blade.md
- source/docs/background-position.blade.md
- source/docs/background-repeat.blade.md
- source/docs/background-size.blade.md
Finishes the Backgrounds section of the documentation
> Update background attachment, position, repeat, and size docs

- source/docs/border-style.blade.md
- source/docs/border-width.blade.md
Finishes the 'Borders' section of the docs
> Update border style and width docs

- source/docs/upgrading-to-v1.blade.md
Fixing additional links in the upgrade guide!
> fix: broken links in additional steps

- source/docs/width.blade.md
Add documentation for all the utilities and add responsive example.
> Update width documentation

- source/manifest.json
Adding `"start_url": "."` in `manifest.json`
> Add start_url i manifest.json

- source/docs/functions-and-directives.blade.md
I found this small typo while reading through the new docs and had a few moments to spare to fix it.
🔥 Love all the work for v1! 🔥
> Fix typo in docs about apply removing important

- source/docs/appearance.blade.md
Document `.appearance-none` reset utility
Preview: https://deploy-preview-192--elated-stonebraker-70896a.netlify.com/docs/appearance
> Add docs for appearance utilities

- source/docs/outline.blade.md
Document `outline-none`
Preview: https://deploy-preview-193--elated-stonebraker-70896a.netlify.com/docs/outline
> Add docs for outline utility

- source/docs/pointer-events.blade.md
Document `pointer-event-auto` and `pointer-event-none`
Preview: https://deploy-preview-194--elated-stonebraker-70896a.netlify.com/docs/pointer-events
> Add docs for point-events utils

- source/docs/user-select.blade.md
Document usage for `select-text` and `select-none`
Preview: https://deploy-preview-191--elated-stonebraker-70896a.netlify.com/docs/user-select
> Add docs for user select utilities

- source/docs/background-repeat.blade.md
> Document `bg-repeat-round` and `bg-repeat-space`

- source/docs/upgrading-to-v1.blade.md
Fixes the link to the default config file - current link leads to 404.
> Fix link to default config file

- config.production.php
- source/_layouts/documentation.blade.php
- source/index.blade.php
Hi @adamwathan 
The navigation currently points to the main site causing a CORS error and preventing DocSearch config running on the new URL.
I've updated the `baseUrl` in the production config file, meta urls and updated the text in the banner.
Thanks for creating such an awesome framework 👍
> v0 Docs: Fix navigation on production and update some stuff

- source/docs/configuring-variants.blade.md
And tweak some other text for clarity
> document the Enable All Variants feature

- source/docs/plugins.blade.md
addBase and config are used in the function body.
> Pass in correct parameters in base style example

- source/docs/font-size.blade.md
> FontSize Customizing Instructions

- config.php
- source/_layouts/documentation.blade.php
Also removes creating an array from and looping through $page in the same function.
Closes #245
> Fix multiple active sidebar items

- source/docs/order.blade.md
Reflects the changes made in https://github.com/tailwindcss/tailwindcss/pull/906.
> Update default config for order

- source/course/the-utility-first-workflow.blade.md
Hey Adam,
I had a shot at writing the notes for one of your new videos. 
The SVG file download is a bit awkward but still better than no file download at all. I took the image from your workcation repo (live demo), I hope that's ok. I adjusted the colors to match the video.
I hope that has saved you up some time, so you can focus on producing further high-quality videos.
Feel free to leave me feedback on my writing style or anything else.
I'm fairly new to open source contributions so I hope this works out.
Best Regards
Tobi
> Adds notes to 'Utility-First Workflow' video (first 3:30 minutes)

- source/docs/configuration.blade.md
documenting https://github.com/tailwindcss/tailwindcss/pull/877
> Document resolveConfig

- source/docs/border-style.blade.md
This PR documents the new `border-double` utility that was introduced in v1.1.0
> Document border-double utility

- source/docs/table-layout.blade.md
Document `.table-auto` and `.table-fixed` utilities
Preview: https://deploy-preview-296--elated-stonebraker-70896a.netlify.com/docs/table-layout
> Add docs for table-layout utilities

- source/docs/customizing-colors.blade.md
- source/docs/using-with-preprocessors.blade.md
This fixes a few typos in the documentation.
> Fix a few typos

- source/docs/border-collapse.blade.md
Document `.border-collapse` and `.border-separate` utilities
Preview: https://deploy-preview-297--elated-stonebraker-70896a.netlify.com/docs/border-collapse
> Add docs for border-collapse utilities

- source/docs/pseudo-class-variants.blade.md
Not entirely sure this is necessary but still wanted to suggest this minor typo.
> Dot missing?

- source/community.blade.md
This adds [Awesome Tailwind CSS](https://github.com/aniftyco/awesome-tailwindcss) to the community section so those coming to the docs/website can find more awesome stuff related to tailwind. 👍
> add awesome tailwind to community section

- source/docs/height.blade.md
> Fixed typos on Height documentation

- source/_layouts/course-lesson.blade.php
- source/course/adapting-the-dropdown-for-mobile.blade.md
- source/course/building-a-navbar-layout-with-flexbox.blade.md
- source/course/composing-utilities-with-apply.blade.md
- source/course/creating-depth-with-shadows-and-layers.blade.md
- source/course/cropping-and-positioning-images.blade.md
- source/course/customizing-your-design-system.blade.md
- source/course/designing-a-badge.blade.md
- source/course/extracting-reusable-components.blade.md
- source/course/hover-focus-and-active-styles.blade.md
- source/course/locking-images-to-a-fixed-aspect-ratio.blade.md
- source/course/making-text-content-feel-designed.blade.md
- source/course/making-the-dropdown-interactive.blade.md
- source/course/making-the-navbar-responsive.blade.md
- source/course/optimizing-for-production.blade.md
- source/course/positioning-the-dropdown-area.blade.md
- source/course/responsive-design.blade.md
- source/course/setting-up-tailwind-and-postcss.blade.md
- source/course/structuring-a-basic-card.blade.md
- source/course/styling-the-basic-dropdown-elements.blade.md
- source/course/the-utility-first-workflow.blade.md
- source/course/toggling-the-navbar-links-on-mobile.blade.md
- source/course/working-with-svg-icons.blade.md
-  Add custom key `sourceCode` for `$page->sourceCode` variable
> Link course chapters to the corresponding subfolders in the source code

- source/docs/controlling-file-size.blade.md
Fixes table layouts on https://tailwindcss.com/docs/controlling-file-size
> fix table layout

- source/docs/installation.blade.md
`installation.blade.md`:
Line 78: "configuration" -> "configuring"
Line 308: grammar & punctuation corrections
> installation.blade.md: Spelling/grammar corrections

- source/docs/configuration.blade.md
> Fix tailwindcss command

- source/docs/display.blade.md
Just adds the inline-grid class to the display page
> Add inline-grid to display page

- source/docs/grid-column.blade.md
Fixes https://github.com/tailwindcss/docs/issues/411.
> Fix incorrect docs for disabling gridColumnEnd

- package-lock.json
- source/_assets/js/app.js
- source/_layouts/documentation.blade.php
- source/_layouts/homepage.blade.php
As the job posting is closed, this shows Tailwind UI widget instead, but keep the A/B code for future use.
> Remove hiring widget

- package.json
@adamwathan You keep forgetting to update the docs 😇
> Update to Tailwind v1.5.1

- README.md
Merging this PR makes the link style consistent in the `README.md`.
> Use the "Composer" text as link

- source/components/forms.blade.md
Change the id of the password input from `inline-username` to `inline-password`.
Totally cosmetic change.
> Fix id of password input

- config.php
- source/_layouts/documentation.blade.php
- Add previous / next links to documentation articles
- Fix #330 
Demonstration bellow 👇 
https://www.loom.com/share/52a62448193d47908d8f2bf093c2c07c
Happy to adjust anything 🙂
> Add prev / next nav links to documentation articles

- src/pages/docs/top-right-bottom-left.mdx
Fixes https://github.com/tailwindlabs/tailwindcss.com/issues/383
> Add missing class to top-right-bottom-left example

- src/pages/components/cards.mdx
Fixes https://github.com/tailwindlabs/tailwindcss.com/issues/405
> Adding vertical spacing on stacked card example

- src/pages/docs/theme.mdx
> Update link to core plugins documentation

- src/pages/docs/customizing-colors.mdx
This is in reaction to https://github.com/tailwindlabs/tailwindcss/discussions/2085
> Include hint about adding single color shades

- src/pages/docs/controlling-file-size.mdx
This fixes a typo in a code snippet.
> fix: fix typo

- src/pages/docs/overflow.mdx
- src/pages/docs/place-self.mdx
- src/pages/docs/space.mdx
Minor grammar tweaks to overflow, place-self, and space docs.
> Make minor grammar tweaks to docs

- src/pages/docs/installation.mdx
- Fixes #540
- update webpack loader configuration example
> - Issue 540 - update webpack loader configuration example

- src/pages/docs/installation.mdx
> Remove reference to Firefox Send

- src/pages/docs/pseudo-class-variants.mdx
> updated focus-visible note to mention chrome support

- src/pages/docs/using-with-preprocessors.mdx
> Updated link URL

- src/pages/docs/configuration.mdx
- src/pages/docs/installation.mdx
> Update tailwind.config.js appearances

- src/pages/docs/top-right-bottom-left.mdx
- src/pages/docs/z-index.mdx
More details in the corresponding [issue](https://github.com/tailwindlabs/tailwindcss.com/issues/548).
> Use explicitly `extend` in the customization section

- src/pages/docs/configuring-variants.mdx
They were bugging me when I was reading the doc.
> Some missing single quotes in configuring-variants.mdx

- src/components/Search.js
update config: https://github.com/algolia/docsearch-configs/pull/2848
> Fix DocSearch - use filter for V2

- src/pages/docs/installation.mdx
Fix 'PostCSS 7 compatibility build' link
> Fix 'PostCSS 7 compatibility build' link

- src/pages/docs/dark-mode.mdx
Fix media query detection if there's no item in localStorage
!'theme' in localStorage is always false
> Fix "Toggling dark mode manually" example

- src/pages/docs/upgrading-to-v2.mdx
Pretty sure this is a typo. Nice work on v2! 🙂
> extends -> extend

- src/pages/docs/responsive-design.mdx
This fixes tailwindlabs/tailwindcss#2897
> docs: remove a responsive-design docs discrepancy

- src/pages/docs/align-content.mdx
fix https://github.com/tailwindlabs/tailwindcss.com/issues/629
> add flex-wrap to align content examples

- src/pages/docs/upgrading-to-v2.mdx
Closes https://github.com/tailwindlabs/tailwindcss.com/issues/604
> add upgrade guide section about font weight name changes for 100 and 200 weights

- src/css/docsearch.css
> Fix: Search Magnifier Icon.

- src/pages/docs/guides/create-react-app.mdx
Will solve the issue I had https://github.com/tailwindlabs/tailwindcss.com/issues/666
> Add jsx to purge

- src/pages/docs/guides/vue-3-vite.mdx
In favor of: https://github.com/tailwindlabs/tailwindcss.com/pull/655
> add index.html to purge option

- src/pages/resources.js
Reverts tailwindlabs/tailwindcss.com#657
> Revert "Use HTTPS for Hero Patterns Website"

- src/pages/resources.js
Reverts tailwindlabs/tailwindcss.com#677
> Revert "Revert "Use HTTPS for Hero Patterns Website""

- src/pages/docs/upgrading-to-v2.mdx
This regex would be useful for people who have a huge amount of leading dots in the project.
> Add the regex that can be used to find and replace all leading dots

- src/pages/docs/dark-mode.mdx
nit but feels cleaner
https://developer.mozilla.org/en-US/docs/Web/API/Document/documentElement
> Simplify access to html element in dark mode snippet

- src/pages/docs/guides/laravel.mdx
Laravel now use laravel mix v6, so I make a change for the version to use latest instead of compat-7, and I also add purge to include "Laravel Views Class Component".
> Update laravel guide

- src/pages/docs/upgrading-to-v2.mdx
This adds breakpoint changes to the upgrade guide. This really got me when I was upgrading
> Add breakpoint changes for upgrade guide

- src/components/Search.js
- src/pages/index.js
Increase search button size in the header, because I always click next to it 🙃
> Increase search button size

- src/pages/docs/align-content.mdx
Included content-evenly for completeness
> Add 'content-evenly' example for align-content.mdx

- src/components/Testimonials.js
> fixes Debbie's testimonial name + role on homepage

- src/pages/docs/breakpoints.mdx
This explains a solution described in [issue #3472](https://github.com/tailwindlabs/tailwindcss/issues/3472)
> [2.x] Docs to solve a problem with custom breakpoints

- src/pages/docs/divide-color.mdx
Replaced **--divide-opacity** with **--tw-divide-opacity** in **src/pages/docs/divide-color.mdx**
> Fix(docs): replace --divide-opacity with --tw-divide-opacity (#755)

- src/pages/docs/configuring-variants.mdx
I have corrected what I reported on this issue #802
> fix documentation

- src/pages/docs/grayscale.mdx
fixed references to `backdrop-filter` on a `filter` utility.
> documentation fix

- src/pages/docs/optimizing-for-production.mdx
> Disable core plugins using strings.

- src/components/home/Performance.js
Closes #780 by updating `KB` references to `kB`
> docs: update KB -> kB

- src/pages/docs/extracting-components.mdx
New to Tailwind and was reviewing the docs for the first time. I spent a while trying to figure out what layers were after learning about extracting components. Couldn't find an explanation for a while, so a link would be helpful.
> Add link to layers for further clarity

- src/pages/docs/just-in-time-mode.mdx
I added a little note about spaces with abitrary values. I feel like it can be worded better but here's my shot.
> A little note about spaces in arbitrary values

- src/pages/docs/installation.mdx
Make sure someone who's following the instructions will install the correct version.
> Add version tailwindcss@^1 to v1 documentation

- src/pages/docs/upgrade-guide.mdx
`'false'` should be without quotes -> `false`
> Typo in upgrade-guide.mdx

- src/pages/blog/tailwindcss-v3/index.mdx
Last line in `## Fancy underline styles`.
> Typo fix: documentaiton -> documentation

- src/navs/documentation.js
- src/pages/docs/scroll-behavior.mdx
Fixes #1016
This PR roughs in the "Scroll Behavior" documentation. It still needs an example, but at least these utilities are discoverable this way.
> Add "Scroll Behavior" documentation

- src/pages/blog/tailwindcss-v3/index.mdx
> Fixing Star Wars location misspelling!

- src/pages/docs/hover-focus-and-other-states.mdx
It seems that this label was written wrong.
> Correct text label ("Username" -> "Email")

- src/pages/docs/content-configuration.mdx
> Adding missing commas

- src/pages/docs/guides/create-react-app.js
This PR updates the "Install Tailwind CSS with Create React App" instructions for the [latest releas (v5.0.0)](https://github.com/facebook/create-react-app/releases/tag/v5.0.0) of Create React App, which supports PostCSS 8.
> Update the "Install Tailwind CSS with Create React App" instructions

- src/pages/docs/divide-width.mdx
I updated the classes in the code to match what was given in the examples.
> Update class names in code

- src/components/ArbitraryValues/index.jsx
https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values is the correct link
> Fix link to arbitrary values

- src/css/utilities.css
What it says on the tin. These are either automatically generated or otherwise unused in the new site.
> Remove unused custom utilities

- src/pages/docs/width.mdx
There's no definition for `w-auto`  or an example of how to use it.
I think there should be at least a Definition that it's the default value,  also an example for reference.
For people who want to know what does it do, or how it can be used. Like the user in this discussion: [#6488](https://github.com/tailwindlabs/tailwindcss/discussions/6488)
Please feel free to made changes, or corrections since English is not my Native Language so there may be some grammar issues. Also if you feel there's a better example.
> Adding definition and example for w-auto

- src/pages/docs/adding-custom-styles.mdx
Documentation update:
https://tailwindcss.com/docs/adding-custom-styles#writing-plugins
after copying the config I have noticed some js errors.
> fix(docs): update custom style config

- src/pages/docs/reusing-styles.mdx
Should read: "each avatar image are repeated five separate times", instead of six.
> Fix number: "six" -> "five"

- src/pages/docs/guides/create-react-app.js
It wasn't clear to me that I needed to upgrade `react-scripts` for my existing project, so I thought it would be good to mention in the guide.
> update react install guide

- src/pages/docs/reusing-styles.mdx
Just fixes the duplicate Team title
> Docs: Fixes title used with map example

- src/pages/docs/preflight.mdx
In `preflight.mdx`, update the link to the raw Preflight CSS file (was for v2 of Tailwind, now is for v3).
> Update link to raw Preflight CSS

- src/pages/docs/presets.mdx
Small fix for anchor at end of https://tailwindcss.com/docs/presets#creating-a-preset section.
> fix: anchor for merging logic at presets doc

- src/pages/docs/line-height.mdx
- src/pages/docs/list-style-position.mdx
- src/pages/docs/list-style-type.mdx
As far as I'm aware, `text-normal` is not a thing, so I replaced it with `text-base`.
> Replace text-normal with text-base

- src/pages/docs/customizing-colors.mdx
Background color link is not properly redirecting to page
> Fix customizing-colors-mdx background-color link

- next.config.js
replaced deprecated querystring with URLSearchParams in nextjs.config.js
> removed deprecated qurystring from next.config.js

- src/layouts/ContentsLayout.js
- src/pages/docs/installation/framework-guides.js
- src/pages/docs/installation/index.js
- src/pages/docs/installation/play-cdn.js
- src/pages/docs/installation/using-postcss.js
> Update content `id` to avoid clashing with page headings

- src/pages/docs/grid-column.mdx
col-span didn't work when trying it, was trying to figure out why it was not compiling, but it's the documentation that doesn't show it correctly.
> col-span-[] doesn't work

- package.json
- yarn.lock
Downgrading to Next 11 to resolve issue with latest version of Headless UI.
> Downgrade to Next 11

- src/pages/docs/align-content.mdx
- src/pages/docs/align-items.mdx
- src/pages/docs/gap.mdx
- src/pages/docs/grid-auto-columns.mdx
- src/pages/docs/grid-auto-rows.mdx
- src/pages/docs/grid-template-rows.mdx
- src/pages/docs/justify-content.mdx
- src/pages/docs/justify-items.mdx
- src/pages/docs/place-content.mdx
- src/pages/docs/place-items.mdx
> :memo: Flex and Grid Doc Improvement

- src/pages/docs/background-position.mdx
updated featuredClass typo for HoverFocusAndOtherStates
> [nit]: updated featuredClass typo

- src/pages/docs/using-with-preprocessors.mdx
https://twitter.com/adamwathan/status/1479536914218864642
Personally, I am using @apply because the docs use it. 
If it is suggested not to, I suggest removing it from the docs
> Remove @apply in docs when possible

- src/pages/docs/font-variant-numeric.mdx
See: https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-afrc
> Fixed stacked fractions OpenType reference

- src/pages/docs/hover-focus-and-other-states.mdx
Fix the grammar in starting paragraph on: https://tailwindcss.com/docs/hover-focus-and-other-states
> Fix grammar in starting paragraph

- src/pages/docs/display.mdx
Remove apostrophe from possessive "its"
> Small grammar fix

- src/components/home/Performance.js
(And because curly apostrophes are great ❤️)
> Switch to curly apostrophe for consistency

- src/pages/docs/guides/parcel.js
Improve Parcel Guide to add `npm init -y` on top of `npm i -D parcel`.
> Improve Parcel Guide

- src/pages/docs/guides/sveltekit.js
The postcss config file already has a .cjs extension.
> Remove unnecessary command

- src/pages/docs/list-style-type.mdx
Could there be anything more vital to this project than having the Fresh Prince lyrics correct? I don't think so. 
This proposed change alters the line "And I like to take a minute and sit right here" to "And I'd like to take a minute just sit right there". To validate:
* https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-the-fresh-prince-of-bel-air-lyrics
* https://www.songlyrics.com/pellek/yo!-home-to-bel-air-the-fresh-prince-of-bel-air-opening-theme-lyrics/
* https://freshprince.fandom.com/wiki/Yo_Home_To_Bel-Air
> Correct Fresh Prince lyrics

- src/pages/docs/plugins.mdx
I came across [this discussion](https://github.com/tailwindlabs/tailwindcss/discussions/7364) while putting together a custom variant and thought it might be nice to document the info/suggestion found there.
> Add custom parent/sibling modifier example

- redirects.json
- src/components/Guides/Snippets.js
- src/components/Guides/TabBar.jsx
- src/hooks/useRouteHash.js
- src/pages/docs/guides/angular.js
- src/pages/docs/guides/create-react-app.js
- src/pages/docs/guides/gatsby.js
- src/pages/docs/guides/laravel.js
- src/pages/docs/guides/meteor.js
- src/pages/docs/guides/nextjs.js
- src/pages/docs/guides/nuxtjs.js
- src/pages/docs/guides/parcel.js
- src/pages/docs/guides/phoenix.js
- src/pages/docs/guides/remix.js
- src/pages/docs/guides/ruby-on-rails.js
- src/pages/docs/guides/solidjs.js
- src/pages/docs/guides/sveltekit.js
- src/pages/docs/guides/symfony.js
- src/pages/docs/guides/vite.js
- src/pages/docs/installation/index.js
- src/pages/docs/installation/play-cdn.js
- src/pages/docs/installation/using-postcss.js
I slso did some duplicate code cleanup in the PR because it's desperately needed.
Fixes #1331
> Rebuild Vite guide to have tabs for React and Vue

- src/components/Header.js
- src/components/HtmlZenGarden.js
- src/components/Steps.js
- src/components/Testimonials.js
- src/components/home/ComponentDriven.js
- src/components/home/DarkMode.js
- src/components/home/EditorTools.js
- src/components/home/Hero.js
- src/components/home/ModernFeatures.js
- src/components/home/ReadyMadeComponents.js
- src/components/home/StateVariants.js
- src/layouts/BlogPostLayout.js
- src/layouts/ContentsLayout.js
- src/pages/index.js
- src/pages/resources.js
- src/utils/mdxComponents.js
Optimize `<img />`
> 1. Adding [`decoding`](https://web.dev/learn/design/responsive-images/#image-decoding) attribute with `async` value which decode the image asynchronously to reduce delay in presenting other content.
> Optimise image by adding decoding 🖼

- src/components/NewsletterForm.js
Adding [autocomplete](https://web.dev/learn/forms/autofill/) attribute in news letter forum for better UX.
> Adding autocomplete attribute for better UX 📧 

- src/components/ThemeToggle.js
- src/pages/_document.js
Adding  `<meta name="theme-color" />` for the website. For more info https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
I choosed `#24729a` as a theme colour hence it looks nice, and that colour in presents in Tailwind CSS logo too.
_Sorry if I made any mistakes :(_
> Updating `<meta name="theme-color" />` 🎨 

- src/pages/docs/place-items.mdx
> Fixes 3 more typos of the kind identified in #1345

- src/pages/docs/cursor.mdx
Fixes: https://github.com/tailwindlabs/tailwindcss.com/issues/1364
> Fix broken cursor images

- src/pages/docs/configuration.mdx
> Fix typo from configuration.mdx file

- src/pages/docs/preflight.mdx
Still needs some writing tweaks
Fixes #1374
> Add docs about `max-width` preflight rules

- src/pages/docs/guides/remix.js
there was a comma at the end of the script which might cause errors, removed it in this pr
> fix typo in remix guide

- src/components/ClassTable.js
> Fix class table overflow

- src/pages/docs/guides/sveltekit.js
https://tailwindcss.com/docs/guides/sveltekit showed just the lines to be added, but wasn't clear about that, which confused people: https://github.com/sveltejs/kit/issues/4382#issuecomment-1292370424. Showing the full file is probably clearer
> clarify SvelteKit example

- src/components/Example.js
- src/pages/docs/columns.mdx
> Hide resize hint on smaller screen sizes

- src/pages/docs/guides/nuxtjs.js
This PR adds a new Nuxt 3 guide to the framework guides section in preparation for the upcoming Nuxt 3 release.
> Add Nuxt 3 guide

- src/pages/docs/backdrop-saturate.mdx
from saturate-{amount} to backdrop-saturate-{amount}
> corrected syntax of backdrop saturate

- src/pages/docs/guides/remix.js
These have nothing to do with the example
> Remove unnecessary dependencies from Remix guide

- src/pages/docs/hover-focus-and-other-states.mdx
Fixes broken link to "Media and feature queries" section.
> Fix link to "Media and feature queries" section

- src/pages/docs/hover-focus-and-other-states.mdx
> Fix typo 'modifers' to 'modifiers'

- src/samples/angular/nav-item.js
> Update nav-item.js to solve #1524

- src/pages/docs/configuration.mdx
> Fix link to default config, which was 404ing

- src/pages/docs/theme.mdx
I have found a few broken links to the default config file. I have updated them to work again : )
> Update broken links in theme.mdx

- src/pages/blog/tailwindcss-v2/index.mdx
- src/pages/docs/configuration.mdx
- src/pages/docs/presets.mdx
- src/pages/docs/theme.mdx
- Fixed some broken or out-of-date links
- Updated Tailwind v2 blog post to point to v2 config file rather than latest
> Fix broken links to default config file

- src/pages/blog/tailwindcss-v3-3/index.mdx
Small fix for some missing backticks on the example
> Remove template string interpolation from example

- src/pages/blog/tailwindcss-v3-3/index.mdx
updated text in example to be the same as the results
> Example text mismatch with result in blogpost for v3.3

- src/pages/docs/customizing-colors.mdx
Update the `Generating colors` section to include the `950` shades.
> Update customizing colors

- src/pages/docs/hover-focus-and-other-states.mdx
Fixing a minor typo in tailwind documentation.
> Fix minor typo

- src/pages/docs/plugins.mdx
- Removed leftover `line-clamp`
- Added `container-queries` section
Let me know if the wording needs to be adjusted at all, I tried to stick to the writing style used.
> Update plugins page

- src/components/Search.js
> Fix search results opening in new tab

- next.config.mjs
> Enable Next.js scroll restoration

- src/pages/docs/guides/remix.js
> docs/guides/remix: update installation docs for remix v2

- src/pages/docs/hover-focus-and-other-states.mdx
Update link to [Subsequent-sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Subsequent-sibling_combinator).
> Update link to "Subsequent-sibling combinator"

- package-lock.json
- package.json
- src/pages/docs/hover-focus-and-other-states.mdx
Adds documentation for `*` modifier at `/hover-focus-and-other-states#styling-direct-children`
> Documents * modifier

- package-lock.json
- package.json
- src/pages/docs/clear.mdx
- src/pages/docs/float.mdx
Adds documentation for `float-start`, `float-end`, `clear-start` and `clear-end`
> Documents float/clear logical properties

- src/pages/docs/hover-focus-and-other-states.mdx
Adds documentation for `has-`, `group-has` and `peer-has`
> Document has selector

- src/pages/docs/text-wrap.mdx
The h3 tags weren't closed and it was irritating me
> Closed h3 tags in text-wrap

- src/pages/docs/hover-focus-and-other-states.mdx
> Fix grammar in hover-focus-and-other-states.mdx

- src/pages/docs/optimizing-for-production.mdx
> Update optimizing-for-production.mdx to fix cssnano url

- src/pages/docs/browser-support.mdx
Update browser support postcss cofig to letest format
> Update postcss config

- package-lock.json
- package.json
- src/components/ColorPaletteReference.js
- src/components/Header.js
- src/components/SnippetGroup.js
- src/components/Steps.js
- src/components/ThemeToggle.js
- src/components/blog/ComboboxDemo.js
- src/layouts/SidebarLayout.js
- src/pages/_document.js
Just some prep for Headless UI v2 stuff
> Update to latest Headless UI insiders release

- src/pages/docs/responsive-design.mdx
The demo is better displayed when resized with the actual resize button thing.
> Minor clarification in Responsive Design

- src/pages/docs/guides/rspack.js
The current link produces a 404.
> Update link to rspack docs

- src/pages/docs/dark-mode.mdx
Use classList.toggle in dark-mode.mdx example
Support : https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle , https://developer.mozilla.org/en-US/docs/Web/API/Element/classList .
> Use classList.toggle in dark-mode.mdx example

- src/blog/tailwindcss-v4/index.mdx
> allowing them to accept certain types arbitrary values
Looks like 'of' is missing here.
> Add missing word in blog post

- src/docs/styling-with-utility-classes.mdx
> Fix incorrect HTML code example

- src/docs/upgrade-guide.mdx
add backdrop blur to migration guide
> chore: add backdrop blur to migration guide

- src/app/blog/[slug]/page.tsx
- src/app/globals.css
- src/components/dynamic-viewport-example.tsx
- src/components/iframe.tsx
- src/mdx-components.tsx
~~Pedantic~~ Minor fixes I added whilst perusing the source code.
> Minor internal fixes

- src/blog/2023-07-18-tailwind-connect-2023-recap/index.mdx
- src/blog/building-react-and-vue-support-for-tailwind-ui/index.mdx
- src/components/syntax-highlighter/theme.json
- src/docs/hover-focus-and-other-states.mdx
- src/docs/order.mdx
> Typos only

- src/blog/tailwindcss-v4/index.mdx
thanks for releasing v4! I can't wait to test it
> fix typo in v4 blog post

- src/docs/colors.mdx
Make sure the displayed code matches the example.
> Fix colors.mdx

- src/docs/min-height.mdx
Complimentary documentation PR for https://github.com/tailwindlabs/tailwindcss/pull/15845.
> Remove `min-h-none`

- src/docs/max-height.mdx
- src/docs/max-width.mdx
Spotted by @minimusubi [on Discord](https://discord.com/channels/486935104384532500/1332680061144403968/1332681392563425383).
> Document `max-w/h-none` utility classes

- src/docs/functions-and-directives.mdx
- Remove erroneous repeated section
- Fix missing `calc()` wrap
> Fix `--spacing()` docs

- src/app/page.tsx
closes #2004
Fixes the quick jump to bottom of the page in safari
This is an existing bug in docsearch: https://github.com/algolia/docsearch/issues/1260
No
> Fix page jump to bottom on safari

- src/docs/border-radius.mdx
Discovered in tailwindlabs/tailwindcss#15986.
> Fix `rounded-lg` documentation

- src/docs/background-image.mdx
> Show type-hint for `background-image`

- src/docs/upgrade-guide.mdx
c.f. https://github.com/tailwindlabs/tailwindcss/issues/15827
> Mention that we're now transitioning `outline-color` in upgrade guide

- src/pages/docs/installation/index.js
match the current `npx init` command
> [DOC] Installation | use `export default` in tailwind.config.js

- src/docs/background-size.mdx
Follow up to #2055, with suggestion https://github.com/tailwindlabs/tailwindcss.com/pull/2055#issuecomment-2636434758 incorporated.
> Use correct inferrable `background-size` value

- src/app/search.css
> Fix dark mode docsearch styles

- src/docs/detecting-classes-in-source-files.mdx
Time wasted? 1hour. 
Hope this clarification helps someone else avoid the rabbit hole I went down
I'm also an idiot, so happy if this gets rejected as such also.
> Clarification on relative paths

- src/docs/max-height.mdx
- src/docs/max-width.mdx
- src/docs/min-height.mdx
See https://github.com/tailwindlabs/tailwindcss/pull/16917
> Document `min-h-auto` and remove `max-w-auto` and `max-h-auto`

- src/docs/grid-column.mdx
- src/docs/grid-row.mdx
See https://github.com/tailwindlabs/tailwindcss/pull/15183
> Document `row-<number>` and `col-<number>`

- src/docs/hover-focus-and-other-states.mdx
Here's what the example looks like when a fine pointer is used:
Here's what the example looks like when a coarse pointer is used:
> Document `pointer-*` and `any-pointer-*` variants

- src/components/stripes.tsx
- src/docs/background-position.mdx
- src/docs/background-size.mdx
- src/docs/object-position.mdx
Changes the api from `bg-left-top` to `bg-top-left` etc
> Update `background-position` and `background-size` docs

- package.json
- pnpm-lock.yaml
> Upgrade Tailwind CSS

- src/app/(docs)/docs/installation/framework-guides/phoenix.tsx
> Bump CLI version in Phoenix guide

- src/app/(docs)/docs/installation/framework-guides/nuxtjs.tsx
This pull request updates the Nuxt installation guide to align with the changes introduced in Nuxt 4. The current instructions can lead to confusion and errors for users setting up a new Nuxt 4 project.
*   Updates the file paths to reflect Nuxt 4's new `app` directory structure. (https://nuxt.com/docs/4.x/guide/directory-structure/app/assets)
*   Updates the `compatibilityDate` in the `nuxt.config.ts` example to a more recent value.
> Update Nuxt framework guide for Nuxt 4
